### ISSUE TITLE
Create a chef supermarket plugin

### ISSUE THREAD

**Issue by kneal** [go-vela/community#101]
## Description

We need a plugin that can upload cookbooks to a chef supermarket.

## Value

Allows Vela users a native and consistent way of uploading Chef cookbooks

## Definition of Done

Plugin exists and can upload a cookbook to the supermarket

## Effort  (Optional)

TBD

## Impacted Personas (Optional)

Vela users using chef

**Comment by plyr4** [comment]
closing based on inactivity, and the downfall of chef
