### ISSUE TITLE
Create JSON Schema to utilize with code editors

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#11]
## Description

Original story: https://github.com/go-vela/types/issues/67

Create a [JSON schema](https://json-schema.org/) to allow code editors to parse the `.vela.yml` and help users understand if the format is valid or not.

The simple steps to test the JSON schema:

1. convert complex `.vela.yml` from yaml to json
2. utilize https://jsonschema.net/home to create JSON schema
3. follow editor specific instructions to utilize the schema for `.vela.yml`
   - VScode docs https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings

## Definition of Done

Users able to configure code editor to utilize published JSON schema for file validation

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

All users modifying `.vela.yml` within any code editor

**Comment by wass3r** [comment]
next release will publish the most recent  version of the schema. will close the story afterwards.

**Comment by wass3r** [comment]
Merged into schema store.
