### ISSUE TITLE
Provide more build variables to templates

### ISSUE THREAD

**Issue by njhartwell** [go-vela/community#113]
## Description

Based on https://target-tts.slack.com/archives/CN8N93Q6L/p1599682098381200

There are a lot of useful environment variables (e.g. branch, tag, commit hash, triggering event) that could be useful in template expressions, but are either not documented or not present (e.g. https://go-vela.github.io/docs/concepts/pipeline/steps/environment/).

## Value

Build configuration can require some conditional logic and string manipulation that is made easier using go templates; a trivial use case from the slack conversation is to pass a build configuration flag using the coalesce method `{{ coalesce .build_version .build_tag .build_commit }}`, i.e. if the user supplied a build_version parameter, use that, otherwise use a the tag, otherwise, the commit hash. The tag and commit hash are currently available as environment variables but do not appear to be available as variables in template context.

## Definition of Done

Template expressions can access commonly used build variables and documentation includes list of these variables and example usage.

## Impacted Personas (Optional)

Users.

**Comment by JordanSussman** [comment]
I believe this is a duplicate of https://github.com/go-vela/community/issues/72.
