### ISSUE TITLE
Cache Plugin - Clean up archive.tgz on restore

### ISSUE THREAD

**Issue by meinenec** [go-vela/community#115]
## Description

currently the restore functionality of the [cache plugin](https://github.com/go-vela/vela-s3-cache) leaves the archive.tgz used in downloading behind after unpacking. This could probably be cleaned up to avoid adding new files to the users workspace.

## Value

Helps keep the users workspace clean and avoids confusion.

## Definition of Done

archive.tgz no longer persists after the step is complete

**Comment by jenmartTarget** [comment]
Started story. Setup plugin with Vela.

Currently mapping out path.

**Comment by jenmartTarget** [comment]
Plugin used 'Archiver'. 

[Documentation](https://godoc.org/github.com/mholt/archiver)

**Comment by jenmartTarget** [comment]
- Object retrieved with ms.GetObjectWithContext
    - Object is decompressed by ‘unarchive’
    - file path is discovered with os.Getwd()
    - Unarchive does not delete old file
    - A delete method will need to be added
    - Recommend os.Remove() method.
