### ISSUE TITLE
Wildcards in jar path not working correctly

### ISSUE THREAD

**Issue by jmagana2000** [go-vela/community#117]
## Description

When certain wildcard patterns are used in sources path to jar file vela does not recognize path and ignores file when loading into artifactory.

## Value

This effects https://github.com/go-vela/vela-artifactory

## Useful Information

Here are the different patterns tested.

- target/scala-2.11/some-jar-file-0.1.jar - **works**
- target/scala-2.11/*.jar - **works**
- target/scala-*/*.jar - doesn't work
- target/scala*/*.jar - doesn't work
- target/**/*.jar - doesn't work
- target/scala-*.*/*.jar - doesn't work

1. What is the output of `vela --version`?

vela version 0.5.4

2. What operating system is being used?

Linux

3. Any other important details?

**Comment by wass3r** [comment]
as an update on this. we are contemplating moving away from using jfrog's cli binary in the plugin and instead using our own artifactory plugin that's already been developed and is in use to provide the same core functionality.

**Comment by wass3rw3rk** [comment]
i believe this is solved by applying 'regexp: true` and enclosing regex in parenthesis as called out in this updated: https://github.com/go-vela/vela-artifactory/pull/174. please reopen if you still see issues.
