### ISSUE TITLE
Worker fails to validate configuration before pulling builds

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#120]
## Description

Currently, the worker will accept builds before it validates the value of `VELA_SERVER_ADDR` is valid. This can cause the following scenario:

1. worker comes online
1. worker connects to redis to pull builds from the queue
1. worker restarts when it attempts to send logs to the server since the `VELA_SERVER_ADDR` value is invalid

My specific testing was utilizing `vela.company.com` instead of `https://vela.company.com`, but any random value should allow reproduction. 

## Value

- Prevent orphaned builds

1. What is the output of `vela --version`?

0.5.2

2. What operating system is being used?

linux

**Comment by ecrupper** [comment]
Closing as this was fixed with the new worker registration pattern + fetching queue credentials from server
