### ISSUE TITLE
API endpoint to cancel orphaned builds

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#121]
## Description

Add some API endpoint(s) to cancel builds that are orphaned. 

## Value

- Administrators no longer need to manually update the postgres database to remove the builds

## Definition of Done

- Administrators are able to complete some API call to force cancel a particular build.

**Comment by meinenec** [comment]
My initial thoughts are to modify the logic in the [cancel build endpoint](https://go-vela.github.io/docs/reference/api/build/cancel/). Currently, if a build is no longer running the api will [return a 400](https://github.com/go-vela/server/blob/master/api/build.go#L1191-L1201). Instead we could set the build to a `canceled` state or add another state to denote that it was orphaned/abandoned.

Any thoughts?
