### ISSUE TITLE
docs: upgrade Hugo to more recent release

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#122]
## Description

Currently, we're using version `0.59.1` of Hugo:

https://github.com/go-vela/docs/blob/master/.github/workflows/build.yml#L28

For building the Vela documentation site:

https://go-vela.github.io/docs/

We should explore upgrading that to a more recent version (at least > `0.70`) to stay up to date 👍 

This was attempted in a previous PR:

https://github.com/go-vela/docs/pull/168

However, when merging that PR it led to issues with content rendering properly on our doc site.

At this time, the issue is believed to be in relation to Hugo changing the `markup` render:

https://github.com/gohugoio/hugo/releases/tag/v0.60.0

## Value

* reduce tech debt
* stay current with Hugo releases

## Definition of Done

The Vela documentation site is using a more recent verison of Hugo (at least > `0.70`)

## Effort  (Optional)

N/A

**Comment by ecrupper** [comment]
Closing as we are now on `0.108.0`.
