### ISSUE TITLE
Get user with GitHub access token

### ISSUE THREAD

**Issue by kneal** [go-vela/community#126]
## Description

Add a new endpoint ability for some to get a user token via their GitHub access token.

## Value

Allows versatility in how users can retrieve the ingo

## Definition of Done

* A new endpoint exists for retrieving the user
* Swagger documentation is updated to include endpoint
* Documentation is updated for new endpoint

**Comment by justsimplify** [comment]
@kneal Should we pass the token as Authorization token or some header as `Token: <token>`?
