### ISSUE TITLE
View services on build page for a repo 

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#13]
## Description

Original story: https://github.com/go-vela/ui/issues/94

Add ability to see services used in pipeline, including their log output.

## Value

Enhance the experience of visually tying the user's pipeline to what the user has defined it to be.

## Definition of Done

User is able to see what services were created in their pipeline and is able to view their respective logs.

## Effort  (Optional)

1 week

## Impacted Personas (Optional)

users

**Comment by wass3r** [comment]
Tasks needed:

- [ ] Figure out how to integrate services into build view visually
  - MVP could be to mimic current steps and have services render as the first items (maybe visually discernible from regular steps)
- [ ] Add API endpoints for service and service logs
- [ ] Extend model to hold services info incl. follow state like steps
- [ ] Add on to build view to render services and logs
- [ ] Extend log actions, and line focus abilities to services logs
- [ ] Add Cypress tests

There is some potential for minor(?) refactor to generalize functionality to not be so "step" focused.
