### ISSUE TITLE
Enhance stages view

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#130]
## Description

Stages view #14 is implemented with https://github.com/go-vela/ui/pull/216

The experience could be enhanced to improve navigation/investigation of stages/steps.

## Definition of Done

Users can navigate/organize staged steps better.

## Effort  (Optional)

2+ days for research, investigation, feedback and implementation.

## Impacted Personas (Optional)

Complex, hard-to-read pipelines

**Comment by ecrupper** [comment]
Closed as complete
