### ISSUE TITLE
Mask secrets exposed in logs

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#136]
## Description

When writing output to logs, mask any exposed secrets with `***` or something similar.

If possible, make it an option to disable the feature or specify which values to ignore.

## Value

Accidents happen. Often times printing a secret during a pipeline is unintentional so masking the value will reduce the area of effect of exposing sensitive information.

## Definition of Done

Secrets cannot be viewed through logs.
Tests and documentation should be added.

## Effort

1 day

**Comment by wass3r** [comment]
completed in referenced, merged PRs.
