### ISSUE TITLE
Set a starting build number

### ISSUE THREAD

**Issue by ZachMayry** [go-vela/community#137]
## Description
For those of us migrating from other CI/CD platforms it would be nice to have our builds continue where we left off.
This allows an internal tool used to delete old docker images to easily tell which build is newer based on the higher number.

## Value
Reduces developer overhead during migration process. 
No need to figure out how to delete images manually or add workarounds.

## Definition of Done
There is a field in the Settings UI that allows you set the starting build number. Example: 30000

**Comment by kneal** [comment]
Team discussed an approach to updating the build number and the desired solution was to create a new field within the repo table and allow users to update that field which would therefore be reflected in the build number. 

This meant in addition to adding the counter management on the repo; we need to write the code to update the build restart and hook process to now depend on the counter as the main incrementer for build numbers. 

The code above linked in Draft PRs, has the required code necessary to do:

* Management of counter field via the `PUT /api/v1/repos/:org/:repo`
* CLI for management of the counter field
* Code to manage the new build number process (repo counter not build number)
* Migration code that will need to be used when the release gets rolled out to consumers

Missing TODOs at this time:

* Updated docs for CLI and API
* Repo settings page in UI needs a section for allowing setting of that field
