### ISSUE TITLE
Authenticate endpoint documented wrong

### ISSUE THREAD

**Issue by slushpupie** [go-vela/community#138]
## Description

It looks like the `/authenticate` endpoint is described as a `GET` request (https://github.com/go-vela/server/blob/master/api/authenticate.go#L24), but expects a form for the body values (https://github.com/go-vela/server/blob/master/api/authenticate.go#L59)

Trying to do an authenticate using the python-sdk isnt working, probably due to this mismatch. 

## Useful Information

python-sdk version: 1.0.0
vela api: 0.6.1

**Comment by jbrockopp** [comment]
@slushpupie I believe this issue has now been fixed by the following change submitted:

https://github.com/go-vela/server/pull/206

Thoughts on us closing this issue?

**Comment by slushpupie** [comment]
Yes, I agree!
