### ISSUE TITLE
View stages on build page for a repo

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#14]
## Description

Original story: https://github.com/go-vela/ui/issues/95

Add ability to see stages used in pipeline, including their log output.

## Value

Enhance the experience of visually tying the user's pipeline to what the user has defined it to be.

## Definition of Done

User is able to see what stages were created in their pipeline and is able to view their respective logs.

## Effort  (Optional)

1 week

## Impacted Personas (Optional)

users

**Comment by kneal** [comment]
MVP Completed within: https://github.com/go-vela/ui/pull/216
