### ISSUE TITLE
Add autofocus to homepage

### ISSUE THREAD

**Issue by bmuenzenmeyer** [go-vela/community#148]
## Description

I use vela many, many times a day. I have 26 favorites across 3 orgs, and counting. The search feature is nice but I wish I could reduce a click before each use.

## Value

Better ux

## Definition of Done

When logging in to Vela lets my instantly search my favorites without my hands leaving the keyboard.

## Effort  (Optional)

1 hour

## Impacted Personas (Optional)

Users

**Comment by wass3r** [comment]
merged with go-vela/ui#231
