### ISSUE TITLE
Colorize log output

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#15]
## Description

Original story: https://github.com/go-vela/ui/issues/141

Log output that contains ANSI control sequence to colorize text is unhandled resulting in them being rendered as-is. Let's convert them and treat affected output respectively.

## Value

Cleaner log output

## Definition of Done

Control characters/escape sequences are converted to respective color. In addition, colors are accessible for currently supported themes.

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

Log output viewers

**Comment by JasonMore** [comment]
+1 Bump I would still appreciate this being resolved :-)

**Comment by wass3r** [comment]
The changes are in https://github.com/go-vela/ui/pull/176. We forgot to close this issue :disappointed:
