### ISSUE TITLE
enhance site navigation (cont.)

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#155]
## Description

As functionality has grown, the top nav has become bloated with buttons that are misaligned and sometimes confusing to the user. This story aims to repurpose the "nav" space in the top right of each page into something along the lines of tabs or a navigation toolbox/dropdown.

## Value

Improving navigation wil reduce latency and friction when using the product.

## Definition of Done

The experience has been improved for all pages of the application.

## Effort  (Optional)

3-4 days

## Impacted Personas (Optional)

Users and admins

**Comment by davidvader** [comment]
This effort has been organized into multiple subparts 
- reorganize Repo layout using tabs
    - requires secrets redesign for viewing repo + org
    - dual-pagination not possible for secrets?
- reorganize Build layout using tabs and collapse actions (when relevant)
    - requires services + pipelines
- simplify crumbs nav 
- reimplement Overview/Source-Repos page using tabs
    - requires api updates for fetching all enabled repos

**Comment by davidvader** [comment]
Repo nav implemented (for the most part)
https://github.com/go-vela/ui/pull/237

Requires affirmation and code review.

**Comment by davidvader** [comment]
Build nav implemented
go-vela/ui#255

**Comment by davidvader** [comment]
Crumbs implemented
https://github.com/go-vela/ui/pull/283

**Comment by ecrupper** [comment]
Closing in favor of https://github.com/go-vela/community/issues/183
