### ISSUE TITLE
Stream logs in near real-time 

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#156]
## Description

The current UI experience when viewing logs can be a bit unappealing since logs appear in delayed chunks instead of the typical streaming.

## Value

- Users are able to see logs in near real-time for a step.

## Definition of Done

- [pkg-executor](https://github.com/go-vela/pkg-executor/blob/master/executor/linux/step.go#L280) updated to send in smaller intervals or stream in real time
- UI updated to poll in smaller intervals or utilize something like [server side event](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) to receive notifications about updates

**Comment by jbrockopp** [comment]
I've started writing a proposal for this:

https://github.com/go-vela/community/pull/339

> NOTE:
>
> The proposal only includes basic information about the enhancement.
>
> More work will be required to evaluate the different options to implement this.
>
> That work should be added directly to the proposal so we can evaluate them.

**Comment by jbrockopp** [comment]
The spike and the proposal have been completed 👍 

This story is intended to actually deliver the functionality of log streaming.

We'll plan to move this story to the next upcoming sprint as we won't be completing this in the current sprint.

**Comment by jbrockopp** [comment]
The proposal has been reviewed and accepted 👍

The work that still needs to be completed has been created as individual stories:

* https://github.com/go-vela/community/issues/366
* https://github.com/go-vela/community/issues/367
* https://github.com/go-vela/community/issues/368
* https://github.com/go-vela/community/issues/369
* https://github.com/go-vela/community/issues/370
