### ISSUE TITLE
Implementation of Rate Limiting

### ISSUE THREAD

**Issue by matt-fevold** [go-vela/community#162]
## Description

Based on the output of #161, implement rate limiting ! More details to come following that story.

**Comment by jbrockopp** [comment]
A PR has been opened for this:

https://github.com/go-vela/types/pull/219

**Comment by jbrockopp** [comment]
A PR has been opened for this:

https://github.com/go-vela/server/pull/558

**Comment by jbrockopp** [comment]
A PR has been opened for this:

https://github.com/go-vela/cli/pull/317

**Comment by jbrockopp** [comment]
A PR has been opened for this:

https://github.com/go-vela/ui/pull/494

**Comment by jbrockopp** [comment]
A PR has been opened for this:

https://github.com/go-vela/docs/pull/270
