### ISSUE TITLE
Update crumbs to match site nav enhancements

### ISSUE THREAD

**Issue by davidvader** [go-vela/community#165]
## Description

low-level issue for completing #155 

Enhance crumbs navigation to provide greater emphasis on the user's current context.

![Screen Shot 2020-12-09 at 2 16 49 PM](https://user-images.githubusercontent.com/48764154/101682465-46c02600-3a29-11eb-9f3f-dfc268435ff5.png)

**Comment by KellyMerrick** [comment]
This has been completed and will be available in release v0.7.0.
