### ISSUE TITLE
Artifactory Plugin - return information during promotion action

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#168]
## Description

In a situation where you accidentally supply `tags` vs `target_tags` for a `docker-promote` action, there is no output with the default debug level. It would be nice to print what action or non-action is being taken using the given parameters so that it's easier to validate that the plugin is performing the desired action. Verbosity can stay minimal by default, but it should show more than nothing.

## Value

Shorten troubleshooting steps
Easier validation

## Definition of Done

The plugin, at the default debug level, returns _something_ in the logs that shares what the plugin is doing with the given parameters.

**Comment by ecrupper** [comment]
Closed as complete, feel free to open new issue if there are specific bits of info missing from the recent plugin updates
