### ISSUE TITLE
Re-enabling a disabled repo unfavorites a favorited repo

### ISSUE THREAD

**Issue by meinenec** [go-vela/community#173]
## Description

I had disabled a repo through the Vela UI, but kept it in my favorites to come back to later. When I returned and enabled the repo, it toggled the favorite status and unfavorited it.

## Value

It's an annoyance 😄 

## Useful Information

I believe this is because we are calling `ToggleFavorite` when we enable a repo.
https://github.com/go-vela/ui/blob/master/src/elm/Main.elm#L771

Feature to auto-favorite was added back in April.
https://github.com/go-vela/ui/pull/143/files

1. What is the output of `vela --version`?

N/A

2. What operating system is being used?

N/A

3. Any other important details?

N/A

**Comment by wass3r** [comment]
the linked pr fixes the issue
