### ISSUE TITLE
Weird time display in UI

### ISSUE THREAD

**Issue by slushpupie** [go-vela/community#176]
## Description

When a build starts, sometimes the displayed time does not make sense.  

For example:
![image](https://user-images.githubusercontent.com/320482/103363420-ad60be80-4a80-11eb-8e3c-06cda2590c20.png)

A build certainly can't start 33 seconds ago _and_ be running for 7 minutes. 

The time shows the steps with incorrect time as well:

![image](https://user-images.githubusercontent.com/320482/103363557-f9136800-4a80-11eb-956e-ec8c1a3fb816.png)

The 8:25 step has not yet completed.  It consists of only a step with `sleep 300` in it.  So the step shouldn't take much more than 5 minutes (plus a few seconds to spawn, etc). 

Once the build completes, all the values get corrected (both the overall build time and the steps)

One possible theory without digging through the code:  When the build is running, the UI takes the value of the build/step start time as supplied by the vela server and compares it to the local time in the browser.  If there is any clock drift it would show up there.  Once the build/step has completed, it becomes simple math of comparing values from the same time source, so drift wont show.

## Value

Its confusing to users to have time displayed that way.  Did the build step really take 8 minutes? Or only 1?

## Useful Information

Vela 0.6.2

**Comment by davidvader** [comment]
We might benefit from setting a `current_reference_time` in the backend to use as the source of truth. That way even if worker time is off by `N` we will have accurate timestamps in the UI.

**Comment by wass3r** [comment]
should have updated some time ago. this ended up being a certain misconfigured worker where NTP wasn't running correctly. feel free to re-open if we you still see the issue.
