### ISSUE TITLE
Unable to update/set password secret using the web ui (vela cmd line works)

### ISSUE THREAD

**Issue by eddie-thp** [go-vela/community#192]
## Unable to update/set password secret using the web ui (vela cmd line works)

Updating a password secret, that contains special characters, using the web ui does not work. Only works when using vela command-line client.

**Sample:** Vela seems to be unable to save or retrieve the correct value for an artifactory password secret with value `abc(cde;:*fgh#}ijkl`, when it was set through the web ui. I've tried setting the value in different ways without quotes, also with double and single quotes.

When the build step tried pushing the image to docker it would fail:

```

1 | time="2021-01-29T19:30:14Z" level=info msg="Vela Docker Plugin" code="https://github.com/go-vela/vela-docker" docs="https://go-vela.github.io/docs/plugins/registry/docker" fields.time="2021-01-29 19:30:14.045911709 +0000 UTC m=+0.037815322"
2 | $ /kaniko/executor --context=. --destination=registry.example.com/org-name/app-name:abc --dockerfile=Dockerfile --verbosity=info
3 | error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "registry.example.com/org-name/app-name:abc": creating push check transport for registry.example.com failed: unsupported status code 401
4 | exit status 1
5 |  

```

Setting it through the cli works.

```
vela update secret --org SOME_ORG --type org --repo '*' --name artifactory_password --value 'abc(cde;:*fgh#}ijkl'
```

## Value

The issue leads to developers spending time trying to troubleshoot problems due to an incorrect update, not knowing the WebUI was unable to properly update the password.

## Useful Information

1. What is the output of `vela --version`?

vela version 0.4.1

2. What operating system is being used?

Mac OS / Google Chrome

3. Any other important details?

Description contains a sample.

**Comment by susangreve** [comment]
Thanks for sending this in! We'll assess priority of this

**Comment by wass3r** [comment]
another test value that exhibits this behavior is `\\n`, works in CLI, not UI

**Comment by wass3r** [comment]
I'm not able to replicate this issue with the reported value of `abc(cde;:*fgh#}ijkl`. When I set that value for a secret and echo it out in my pipeline, I get the exact value back.

Here is a basic pipeline example with an *org* secret named "test" that was set to `abc(cde;:*fgh#}ijkl` via the UI:
```yaml
version: "1"

steps:
  - name: echo
    image: alpine:latest
    secrets: [ test ]
    commands:
      - echo "$TEST"

secrets:
  - name: test
    key: wass3r/test
    engine: native
    type: org
```

In the output for the build I can see that exact value echo'd back.

![image](https://user-images.githubusercontent.com/1301201/126043050-ac2f3a9a-dc4a-4ba5-97f9-a3061d2e43c4.png)


So, there might be something else going on in your case?

As I commented I see an issue with `\\n`. However, contrary to my previous comment, it happens with either CLI or UI. The output is `\n` instead. The note on escaping `\` from https://go-vela.github.io/docs/reference/cli/secret/add/ seems mostly true. In the example of `\\n`, modifying the value to `\\\\n` when adding the secret yielded the expected the result.

Was there a different special character in play? It might be specific to the docker plugin, too. I will do some testing there.

**Comment by wass3r** [comment]
Possibly something going here with regard to the Docker plugin. Maybe the `:` in your password is the culprit 🤔 :
- https://github.com/go-vela/vela-docker/blob/fdce13b2ae999b9169e86b9c07802e5afe1d9880/cmd/vela-docker/registry.go#L95-L97
- https://github.com/go-vela/vela-docker/blob/fdce13b2ae999b9169e86b9c07802e5afe1d9880/cmd/vela-docker/registry.go#L21

**Comment by wass3r** [comment]
based on the above comments and testing, i don't believe this is an issue. if you have further evidence to the contrary, please feel free to comment and we can reopen.
