### ISSUE TITLE
vela-downstream read from NETRC environment variables

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#193]
## Description

It'd be a great QOL enhancement to have the [go-vela/vela-downstream](https://github.com/go-vela/vela-downstream) read from the NETRC credentials as a form of fallback authentication.

Currently, we allow users to provide their own GitHub PAT to the [go-vela/vela-downstream](https://github.com/go-vela/vela-downstream) plugin to authenticate with Vela.

It'd be a great QOL enhancement to have the plugin read from the NETRC credentials as a form of fallback authentication.

The idea would be that if the user doesn't provide their own GitHub PAT to the plugin, then we default to using the NETRC credentials.

In the event the user does provide their own GitHub PAT, then that would override using the NETRC credentials.

One caveat worth mentioning to this approach is that the user who's NETRC creds are injected would have to have sufficient privileges to the downstream repository trying to be triggered.

Please see https://github.com/go-vela/community/issues/190 and https://github.com/go-vela/vela-downstream/pull/37 for more information.

## Value

Decrease barrier to entry for users with the Downstream plugin

## Definition of Done

A user can use the `vela-downstream` plugin to trigger a downstream repository with the NETRC credentials.

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

users of the `vela-downstream` plugin

**Comment by JohnTrammellTarget** [comment]
Thanks, this is in our backlog and we are assessing its priority.

**Comment by ecrupper** [comment]
Going to close this issue, as the Vela team would rather prioritize migration to GitHub apps with a more scoped form of authentication. See https://github.com/go-vela/community/issues/804. Feel free to re-open
