### ISSUE TITLE
Invalid check for images that contain variable interpolation

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#197]
## Description

Currently, https://github.com/go-vela/types/blob/4495c6cec9e4b0e9c97af87e069acb86af31a99c/yaml/step.go#L178 returns failures for images like `alpine:${VELA_BUILD_COMMIT:0:7}`. 

## Value

Users are once again able to utilize variables within the `image` parameter.

## Useful Information

Server is utilizing v0.7.1.

**Comment by jbrockopp** [comment]
Closing this in favor of what was agreed on https://github.com/go-vela/types/pull/143#issuecomment-773399836
