### ISSUE TITLE
Put the version number visibly in the UI

### ISSUE THREAD

**Issue by slushpupie** [go-vela/community#205]
## Description

Put the version of Vela somewhere in the UI

For example, the footer on Github Enterprise includes the current release version number.

## Value

Makes it easy for users to identify which version is running, and potentially which version of documentation to look at or which features are available.

## Definition of Done

Version number is visible somewhere in the UI

## Effort  (Optional)

Likely low, but I'm only guessing.

**Comment by davidvader** [comment]
this information is currently available at `GET` - `vela-server.com/version` and could easily be integrated into the UI, however it requires discussion due to lack of auth required to hit the endpoint

**Comment by susangreve** [comment]
Duplicate of: #95

**Comment by cognifloyd** [comment]
As noted, this is a duplicate of #95.
