### ISSUE TITLE
Server needs to proxy worker endpoints to manage builds

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#21]
## Description

Original story: https://github.com/go-vela/server/issues/86

Provide a mechanism for users to manage (cancel/kill) a running build

## Value

Terminate a long running (potentially rogue?) process
Prevent a misconfigured build from harming the system(s) it interacts with

## Definition of Done

A user can send an API call to the server that will handle the communication with the worker to manage the build.

## Effort  (Optional)

2 weeks

## Impacted Personas (Optional)

users

**Comment by plyr4** [comment]
closed as complete
