### ISSUE TITLE
Fix style in build history widget

### ISSUE THREAD

**Issue by davidvader** [go-vela/community#223]
## Description

long host names cause funky styling, its possible the other fields are impacted as well

![Screen Shot 2021-02-25 at 11 05 36 AM](https://user-images.githubusercontent.com/48764154/109189401-99bc9600-7759-11eb-9709-07d7e31e6e2f.png)

## Solution

use `flex` to strictly align fields to the right

**Comment by wass3r** [comment]
this is already fixed in: https://github.com/go-vela/ui/pull/389
