### ISSUE TITLE
Display shows incorrect date for Recent Build hoverover

### ISSUE THREAD

**Issue by delta592** [go-vela/community#244]
## Description

When hovering over the recent build section, for the most recent build while running, the date stamp is 'December 31st 1969' for the Finished section.

## Value

Finished date for a running build should be blank, or at least not display a date in the past.

## Useful Information

See attached screen capture

**Comment by delta592** [comment]
<img width="1049" alt="Screen Shot 2021-03-24 at 08 48 03" src="https://user-images.githubusercontent.com/22849185/112680269-2af75900-8e3b-11eb-9a7d-cdfd03fbeb6a.png">

**Comment by delta592** [comment]
<img width="1049" alt="Screen Shot 2021-03-24 at 08 48 03 copy" src="https://user-images.githubusercontent.com/22849185/112680572-8aedff80-8e3b-11eb-8052-81a3e6ecc6a7.png">

**Comment by davidvader** [comment]
closed via
