### ISSUE TITLE
Environment Variables tab

### ISSUE THREAD

**Issue by kennyli92** [go-vela/community#255]
## Description

Have a tab in the UI that supports `Environment Variables` similar to `Secrets`, but the values are obviously safe to expose

## Value

Although we can define `Environment Variables` in the Vela script, we cannot persist changes of the `Environment Variable`. Similar to `Secrets`, it would be helpful if we're provided CLI to get, view, and update `Environment Variables`. This would be very helpful in the case of automating the management of release versions, and perhaps other scenarios I haven't thought of.

## Definition of Done

When there is an `Environment Variables` tab in the UI. The functionality should match that of `Secrets`, except the values are exposed.

**Comment by kneal** [comment]
I've actually seen some other CIs display the injected envionrment at the beginning of a pipeline run. That could look something like this


![image (5)](https://user-images.githubusercontent.com/12552518/116109018-0bda2a00-a67a-11eb-8e70-cef253256021.png)


Is that kinda what you're getting at?

Or are you looking more for global variables that are injected into every step?

**Comment by kennyli92** [comment]
Kinda. I suppose the Environment Variable can be step specific or global. The one feature I really like about `Secrets` is that we can change and persist the value with the provided CLI. This isn't really an urgent ask since I'm already using `Secrets` to do what I need. I'm using `Secrets` to manage my app's version, but it's really not confidential. The caveat with `Secrets` is that there is no way for me to see the latest value (app's version in my case) from the UI.

**Comment by ecrupper** [comment]
Closing as it is stale, but there is a proposal out there (https://github.com/go-vela/community/pull/789) which could potentially be related to this. Feel free to reopen
