### ISSUE TITLE
Update templates to allow them to call templates. 

### ISSUE THREAD

**Issue by kneal** [go-vela/community#256]
## Description

We are looking to add the ability to call a template from within a template. 

_One thing to think about during implementation is rate-limiting when calling a large number of templates. May need special call-outs in the docs for limitations._

## Value

This would allow users to create more granular templates that are specific to a single workflow. 

## Definition of Done

Templates can call other templates

**Comment by carlosrfernandez** [comment]
Template composition is pretty standard nowadays. It would be great to support this feature.

**Comment by RiviqVH** [comment]
Would be extremely beneficial to be able to define singular tasks as templates, then compile a list of templates that is then called from the main pipeline as a template. Keeps the codebase cleaner and is way more reusable!
