### ISSUE TITLE
Makisu is deprecated upstream and ceases public development 2021-05-04

### ISSUE THREAD

**Issue by colindean** [go-vela/community#258]
## Description

https://github.com/uber/makisu/issues/365 says:

> This is a notice that the makisu project is being deprecated and will be archived by the 4th of May 2021. The project will be archived into the Uber Archive GitHub organization. If you have any concerns or thoughts regarding the deprecation of makisu, please let us know by commenting this issue.
>
> […]
>
> Makisu is still being used internally, but the team does not have the resources to maintain the project publicly.

## Impact

While this doesn't _kill_ the Makisu plugin for Vela, it likely means that it won't see any additional releases or bugfixes from Uber for Makisu itself.

**Comment by susangreve** [comment]
Thanks for bringing this up! We will assess how to handle this

**Comment by wass3r** [comment]
plugin has been discontinued
