### ISSUE TITLE
Respond to Github PR comment events

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#26]
## Description

Original story: https://github.com/go-vela/server/issues/112

Respond to more PR comment events to trigger builds
- pull request review comments
- pull request reviews

## Value

Support more diverse workflows

## Definition of Done

A user can successfully trigger a build via a PR comment on GitHub.

## Effort  (Optional)

1 week

## Impacted Personas (Optional)

users

**Comment by wass3r** [comment]
this has been addressed in https://github.com/go-vela/types/pull/175
