### ISSUE TITLE
CLI should surface network errors rather than panicking

### ISSUE THREAD

**Issue by zapplebee** [go-vela/community#266]
## Description

Currently, the CLI fails angrily on when it cannot access the internet and gives no indication that that is the issue.

```
vela login --api.addr https://vela-server.corporatenetworkhost
vela login
? Open https://vela-server.corporatenetworkhost/ in your browser and complete authentication (Press Enter to confirm)? [Y/n] █
```

This successfully opens the login screen because it is available from the corporate network.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14a48cb]

goroutine 1 [running]:
github.com/go-vela/cli/action/login.(*Config).Tokens(0xc0001cb2c0, 0xc0000265a0, 0xc00004c0ca, 0x19, 0x1, 0x0)
	/github/workspace/action/login/login.go:98 +0x3ab
github.com/go-vela/cli/action/login.(*Config).Login(0xc0001cb2c0, 0xc0000265a0, 0xc0001b0000, 0x0)
	/github/workspace/action/login/login.go:61 +0x2ac
github.com/go-vela/cli/action.runLogin(0xc000117b00, 0x6, 0xa)
	/github/workspace/action/login.go:117 +0x148
github.com/urfave/cli/v2.(*Command).Run(0x30c3dc0, 0xc000117700, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0003a0820, 0x26eeaf0, 0xc0001ac160, 0xc0001b6000, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/github/workspace/cmd/vela-cli/main.go:128 +0xe05
```

The CLI should expose its network error.

## Value

It was unclear why login failed. In my case, all I had to do was set my proxy variables, but there was no indication that internet access was the culprit on this failure.

## Definition of Done

CLI exposes network errors instead of panicking.

## Impacted Personas (Optional)

Anyone using the CLI within a controlled network environment.

**Comment by zapplebee** [comment]
Additional context:

This issue was discovered while connected to our corporate VPN with the proxy disabled.

Meaning, there was a clear network path to the vela instance, https://vela-server.corporatenetworkhost, but not to the rest of the internet.

**Comment by JordanSussman** [comment]
Looks like this is being caused since https://github.com/go-vela/sdk-go/blob/master/vela/authentication.go#L176 returns nil instead of the actual response.
