### ISSUE TITLE
JWT expiration & refresh token

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#29]
## Description

Original story: https://github.com/go-vela/server/issues/134

_Note: This change will be taking place in multiple places/repos - other stories to follow._

Currently, JWT returned by the server lives indefinitely. The client is responsible for retiring it. This change will introduce expiration for the JWT to make it short-lived and introduce a long-lived refresh token.

## Value

Improved security

## Definition of Done

* Server returns JWT + Refresh Token with expiration.
* Provides means to retrieve new JWT via refresh token endpoint.
* Expired JWT, Refresh Token prevents access.

## Effort  (Optional)

2 weeks

## Impacted Personas (Optional)

users

**Comment by wass3r** [comment]
Will move to v0.6.0
