### ISSUE TITLE
Dev Tooling for Template and .vela file debugging

### ISSUE THREAD

**Issue by aceluby** [go-vela/community#292]
## Description

Currently, the only way to see if your vela file is correct is to try to submit it to vela and see if it fails.  If it does fail, the only thing you can go on is what the api response gives you.

What would be great is if there was some sort of offline tool, or better yet - an IntelliJ plugin, that I could submit a vela file/template to check for errors, debug, and see what the final vela file would be. 

## Value

1. This would make the barrier to entry significantly smaller for vela as a whole and template usage
2. It would allow devs to test out and use more complex logic inside templates 
3. It would decrease the number of requests to the vela server as some percentage are just seeing if the file works

## Definition of Done

* An offline option to run and test files and templates
* Documentation on how to use the tooling

## Effort  (Optional)

* Unknown - not sure how the current api is set up and how easy it would be to port the code to a self contained module or IntelliJ plugin

## Impacted Personas (Optional)

* Developers using vela for builds

**Comment by benzvan** [comment]
We haven't looked into this but maybe the go modules in vela that process the templates could be used to process the templates locally?

I've tried using the vela CLI to validate files and I haven't gotten it to fail on one yet.

**Comment by plyr4** [comment]
we've made a lot of improvements to the CLI regarding `validate pipeline` and `exec pipeline`, please check them out and let us know how we can make it better.
for example, we now support template expansion with local files! (among many other cool improvements like `exec` environment)

feel free to open again with more feedback, thanks!
