### ISSUE TITLE
Kaniko Plugin - allows invalid reference format for tags

### ISSUE THREAD

**Issue by Cappo** [go-vela/community#301]
## Description

Valid Docker tags are described as:
>A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

The Kaniko plugin does not seem to check for this and allows a `-` to prefix the tag which means that after it's published it cannot be pulled later.

Expected behavior would be to check the given `tags` parameter for invalid tags and reject them, failing the step.

## Value

Saves time debugging why tooling can't pull the published image.

## Useful Information

Tested on `v0.6.0`

**Comment by wass3r** [comment]
Additional reference: https://docs.docker.com/engine/reference/commandline/tag/#extended-description

I believe this is the regex docker matches against: `[\w][\w.-]{0,127}` - i see it mentioned in a number of places in docker's codebase.

example: https://github.com/moby/moby/blob/cc5a381cbcc06e5cd71fc50a8989c36f6dad9ac3/vendor/github.com/docker/distribution/reference/reference.go#L15

**Comment by wass3r** [comment]
Kaniko does this:
https://github.com/GoogleContainerTools/kaniko/blob/a0c96b4edcaeee437243484f5880833518d06551/vendor/github.com/google/go-containerregistry/pkg/name/tag.go#L67-L69

which leads to:
https://github.com/GoogleContainerTools/kaniko/blob/a0c96b4edcaeee437243484f5880833518d06551/vendor/github.com/google/go-containerregistry/pkg/name/check.go#L35-L43

which is just checking for allowed characters:
https://github.com/GoogleContainerTools/kaniko/blob/a0c96b4edcaeee437243484f5880833518d06551/vendor/github.com/google/go-containerregistry/pkg/name/tag.go#L22-L24

anecdotally, there is a TODO to use docker's regex in the last link
