### ISSUE TITLE
Make the VELA_BUILD_TAG value more prominent in the UI

### ISSUE THREAD

**Issue by dan-kirberger** [go-vela/community#310]
## Description
![image](https://user-images.githubusercontent.com/16195927/123353324-e311cc00-d526-11eb-89e7-488f56296b96.png)
It would be very handy if the value of VELA_BUILD_TAG was more prominently displayed in the UI. On this quick info area perhaps, or also when hovering over "recent builds":

![image](https://user-images.githubusercontent.com/16195927/123353381-00df3100-d527-11eb-8793-b7a2e1200997.png)

We typically use tags like "v1.0.0" or "rc2.0.0" which is much more meaningful than the commit hash.

**Comment by wass3r** [comment]
partially addressed via https://github.com/go-vela/ui/pull/427; we can keep it open for the hover card 👍🏼

**Comment by JordanSussman** [comment]
These enhancements were added within v0.10.0 of Vela.
