### ISSUE TITLE
Add JSON output to CLI pipeline validation

### ISSUE THREAD

**Issue by colindean** [go-vela/community#313]
## Description

The Vela CLI tool can validate `.vela.yml` but it just outputs [an "it's ok" message](https://github.com/go-vela/cli/blob/8ac3e957193754f7fb7587cb408bf3cd3a56b66f/action/pipeline/validate.go#L115) when evaluating locally. It'd be great if it could output the config as JSON as seemingly the remote validation can.

## Value

I'd like to extract information from .vela.yml via the commonly-installed `jq` program without having to install other tooling, e.g. [`yq`](https://github.com/mikefarah/yq) or writing a script that converts YAML to JSON but does so without validation and with a different YAML parser that may produce a different JSON result than Go's YAML library that Vela uses.

My particular use case is extracting the Docker tag specified in the Vela config for use in a dev env build script.

## Definition of Done

The `vela validate pipeline` program takes an option `--output json` when in local mode and produces a JSON version of the `.vela.yml`.

## Impacted Personas (Optional)

Folks building tools around Vela would benefit from being able to deal with materialized JSON instead of YAML.

**Comment by benzvan** [comment]
I have also found that this `it's ok` message is returned even if the .vela.yml is not a yaml file.

**Comment by susangreve** [comment]
Thanks for opening this! We have added it to the backlog and will assess priority

**Comment by colindean** [comment]
Perhaps also an option to resolve templates, but with an acknowledgement that since templates can contain logic, they may not be expandable by the tool. I guess this _could_ be worked around by allowing the user to specify environment variable values and telling the user what they need to supply when it's missing.

Bonus points if there's a way for Go templates to list what variables they expect…

**Comment by colindean** [comment]
The current behavior as of v0.17.0 now outputs the rendered template, but it also still outputs the "is valid" message, so piping the output to a `yaml2json` converter isn't possible without first removing the first line.

https://github.com/go-vela/cli/blob/641fb4c22d9e4ef1409ca564da665e322aa74931/action/pipeline/validate.go#L117-L126

**Comment by plyr4** [comment]
closed as complete via #791 and #313
