### ISSUE TITLE
vela-artifactory doesn't fail the pipeline on errors

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#32]
## Description

Original story: https://github.com/go-vela/vela-artifactory/issues/44

```
[Error] [Thread 2] Artifactory response: 409 Conflict
[Error] Failed uploading 1 artifacts.
```

this example output would still leave the step it was used on as a successful step

## Useful Information

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?

**Comment by jbrockopp** [comment]
Extra information from @meinenec:

> We may be able to use this to get the correct status:
>
> https://github.com/jfrog/jfrog-client-go/blob/master/artifactory/services/upload.go#L54
>
> and check it here
>
> https://github.com/go-vela/vela-artifactory/blob/master/cmd/vela-artifactory/upload.go#L56

**Comment by Cappo** [comment]
https://github.com/jfrog/jfrog-client-go/blob/master/artifactory/services/upload.go#L76

New link for UploadFiles API

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-artifactory/releases/tag/v0.5.0 should take care of this. please open another issue if you still encounter this.
