### ISSUE TITLE
`VELA_REPO_BRANCH` does not follow current default repository branch

### ISSUE THREAD

**Issue by 10hendersonm** [go-vela/community#325]
### Outcome

The [`VELA_REPO_BRANCH` environment variable](https://go-vela.github.io/docs/reference/environment/variables/#repository-environment-variables) is set when the repository is enabled in Vela rather than periodically or on a per-event basis.

### Expected Outcome

The `VELA_REPO_BRANCH` environment variable should resolve the current default branch of the repository.

### Workaround

Disable and re-enable the repository in Vela settings.

### Reproduction Steps

<details><summary>Click to Expand</summary>

1. Create empty repo
2. Enable new empty repo in Vela
2. Commit and push this `.vela.yml` to `master`
    - ```yml
      version: '1'
      
      steps:
        - name: happens_always
          image: alpine
          commands:
            - echo "Hello World 1"
      
        - name: happens_on_default_branch
          image: alpine
          ruleset:
            branch: '${VELA_REPO_BRANCH}'
          commands:
            - echo "Hello World 2"
      ```
    - Result: ![](https://user-images.githubusercontent.com/14095644/125298188-8b78ac00-e2ed-11eb-91d3-5883abc33c3b.png)
4. Cut new branch `main` from `master`
    - ![image](https://user-images.githubusercontent.com/14095644/125299483-ce874f00-e2ee-11eb-8cf7-a15cbf9afb39.png)
    - Result (this is expected to only trigger the `happens_always` step): ![image](https://user-images.githubusercontent.com/14095644/125299235-9253ee80-e2ee-11eb-9a17-6d0e73502c2b.png)
5. Change default branch to `main`
    - ![image](https://user-images.githubusercontent.com/14095644/125299599-e8c12d00-e2ee-11eb-89fc-b888d473a1b4.png)
6. Restart build 2 (the push event for `main`)
    - Result (`happens_on_default_branch` does **not** trigger): ![image](https://user-images.githubusercontent.com/14095644/125299710-0393a180-e2ef-11eb-8328-f7d9d8c301f9.png)

</details>

### Proposed Solution

The webhook payload contains a `repository.default_branch` (and `repository.master_branch`) parameter which appears to stay up-to-date. I don't know the underlying systems / architecture to say how detailed of a change this feature would be, but the data does exist.

Original webhook (from `Reproduction Steps` above):

```json
{
  ...,
  "repository": {
    ...,
    "default_branch": "master",
    ...,
    "master_branch": "master",
    ...
  },
  ...
}
```

Adding a new push:

```json
{
  ...,
  "repository": {
    ...,
    "default_branch": "main",
    ...,
    "master_branch": "main",
    ...
  },
  ...
}
```

### More Details / Context

My team publishes a Vela template which can accept custom rulesets. Our documented guidance suggests users leverage this ruleset:
```yml
ruleset:
  event: push
  branch: '${VELA_REPO_BRANCH}'
```

Unfortunately, as this lives in our documentation, I'm looking out for future users who are uninformed of this functionality rather than seeking a one-time workaround (see above) to fix my repository.

## Value

- It's not intuitive that the `default branch of the repository` in Vela would be the default branch when the repository was enabled
- This would prevent needing to disable and enable repos

## Useful Information

1. What is the output of `vela --version`?

Locally my CLI version is `vela version 0.4.1`, but I didn't leverage the CLI for the reproduction steps. I'm unsure what version the server is.

2. What operating system is being used?

N/A

3. Any other important details?

**Comment by susangreve** [comment]
Thanks for opening this Marty! We have added it to our backlog and will assess priority
