### ISSUE TITLE
Allow the base Vela pipeline file to be templated

### ISSUE THREAD

**Issue by kneal** [go-vela/community#326]
## Description

The `.vela.yml` file that lives in the repo should be allowed to have template usage on it. The goal would be to write it in a way that supports both Go templates and Starlark. So, we will need to expand the base file to include `.vela.star` and `.vela.py` files in the base repo. 

## Value

This would allow consumers to template out stages or more dynamically build pipeline files directly in the source repository running a pipeline.

## Definition of Done

The pipeline file that lives in the base activated repo can be templates with all available template languages. 

## Impacted Personas (Optional)

N/A. Users will need to opt into a configuration with a setting on the repo. No breaking change occurring.

**Comment by kneal** [comment]
This feature was created during the [Target/Cargil hackathon](https://github.com/go-vela/community/discussions/321). 

The following PRs were competed during the hack:

- https://github.com/go-vela/types/pull/188
- https://github.com/go-vela/compiler/pull/199
- https://github.com/go-vela/server/pull/444


The following work needs to be complete to finish off the feature:

- [ ] Add enabling pipeline type to UI on the repo settings page
- [ ] Write a migration script for adding a new field in repos table

**Comment by GregoryDosh** [comment]
Would allowing the CI files to be named `.vela.py` be confusing in that it really isn't Python, but Starlark instead? What happens in the future if you DO support Python based CI config?

**Comment by kneal** [comment]
That's fair, we do support it for templates today but it's not documented. So, this would be calling attention to that feature/option

**Comment by kneal** [comment]
_Add enabling pipeline type to UI on the repo settings page_
https://github.com/go-vela/ui/pull/421

**Comment by kneal** [comment]
This PR adds the framework to accomplish the task of migrating the new defaulted fields in the database
https://github.com/go-vela/community/pull/338
