### ISSUE TITLE
Error message from Template function is nonspecific.

### ISSUE THREAD

**Issue by benzvan** [go-vela/community#330]
## Description

The error `"no valid template found at %s/%s/%s", s.Org, s.Repo, s.Name` is returned on a 404 from github. It should be clearer if no template was found or if a template was found but it was not valid.

https://github.com/go-vela/compiler/blob/43afa7ea39525e906473b7fe25dfcd8871acbe8e/registry/github/template.go#L59

## Value

When running a vela build, I would like to know if the template is broken or if the url is incorrect or some other error.

## Useful Information

1. What is the output of `vela --version`?

Not relevant since this is a server-side/library issue

2. What operating system is being used?

3. Any other important details?

**Comment by meinenec** [comment]
I believe this only happens on a 404 (like you mentioned) and an actually invalid (but found) template returns a more meaningful error.

I'll open a PR to suggest changing that error message to `"no Vela template found at %s/%s/%s", s.Org, s.Repo, s.Name`

@benzvan Let me know if you know of any test cases that contradict this. I'm trying to find a case where we see this error message even though a template exists.

**Comment by xordspar0** [comment]
> I believe this only happens on a 404

When I was talking to Ben about this and looking through the code, that was my suspicion as well. Updating the error message makes sense to me.
