### ISSUE TITLE
Setup with public GitHub.com fails

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#335]
## Description

Currently when you use the following:
`VELA_SOURCE_ADDR=https://github.com`

The server will fail with this in the server logs:
```
Error #01: unable to authenticate user: GET https://github.com/api/v3/user: 404  []
```
The API path was determined to take on that of a GitHub Enterprise Installation.

This happens because of this check:
https://github.com/go-vela/server/blob/8a15f74f3a696ca1050008b92e27f57f5ba43ec3/source/github/opts.go#L30-L33

Where it's comparing the supplied value to:
https://github.com/go-vela/server/blob/8a15f74f3a696ca1050008b92e27f57f5ba43ec3/source/github/github.go#L17

Since, `https://github.com` != `https://github.com/`, it assumes it's a Enterprise installation.

If you attempt to correct the issue by setting the following:
`VELA_SOURCE_ADDR=https://github.com/`

You will encounter this error in the server logs:
```
{"level":"fatal","msg":"source address must not have trailing slash","time":"2021-07-17T23:27:15Z"}
```

This happens due to the validation happening here:
https://github.com/go-vela/server/blob/8a15f74f3a696ca1050008b92e27f57f5ba43ec3/source/setup.go#L89-L91

Consequently, one is not able to stand up a Vela stack pointing at public GitHub without some server modifications.

## Value

For administrators:
Administrators are able to test out Vela by pointing it at public GitHub.com

For contributors:
Contributors are not required to have a GitHub Enterprise installation to stand up a local stack for development.

## Useful Information

1. What is the output of `vela --version`?

Tested on latest version in `master` branch.

2. What operating system is being used?

Linux

3. Any other important details?

( not sure why permalinking to code is not showing previews 😢 )

**Comment by ryanpodonnell1** [comment]
I'll take a stab at this
