### ISSUE TITLE
Show the PR number or Tag in the build

### ISSUE THREAD

**Issue by JayCeeJr** [go-vela/community#350]
## Description

Show the PR number or Tag in the build screen along with the commit hash

## Value

Provides a quick glance at what tag or PR the build is for, so you don't need to click through to git to find out.

## Definition of Done

PR number and Tag show in the build menu with a link to github

## Effort  (Optional)

Minimal

## Impacted Personas (Optional)

All users

**Comment by wass3r** [comment]
related: https://github.com/go-vela/community/issues/310

**Comment by wass3r** [comment]
completed via: https://github.com/go-vela/ui/pull/427
