### ISSUE TITLE
deleted comment triggers event

### ISSUE THREAD

**Issue by davidvader** [go-vela/community#351]
## Description

Deleting a comment with "some content" will trigger the comment event for "some content".

I would argue this is a bug.

We could potentially
- filter out `"action": "deleted"` events via the webhook payload
- add a ruleset field for determining comment `created` / `deleted` 

## Reproduce

```
ruleset:
  event: [ comment ]
  comment: [ "some content" ]
```

- Create pull request
- Comment 'some content'
- Delete comment

2 comment builds will trigger

**Comment by wass3r** [comment]
fixed in https://github.com/go-vela/server/pull/486
