### ISSUE TITLE
UI builds linked to wrong build

### ISSUE THREAD

**Issue by matt-fevold** [go-vela/community#353]
## Description

**For the latest v0.9 RC**

 repo builds page: for certain repos, the links in the build list lead to <build number> - 1, ie. build 184 links to build 183

**Comment by matt-fevold** [comment]
This also seems to be an issue in the cli 
`vela view build --org ORGNAME --repo vela-test --build 268`  produced the same error.

**Comment by wass3r** [comment]
probably related: https://github.com/go-vela/community/issues/322
