### ISSUE TITLE
repo page: org link disappears when on deployment tab.

### ISSUE THREAD

**Issue by matt-fevold** [go-vela/community#356]
## Description

repo page: org link disappears when on deployment tab.

Screenshot with org link on builds tab:
<img width="315" alt="Screen Shot 2021-08-09 at 4 02 36 PM" src="https://user-images.githubusercontent.com/15000375/128774256-8378768c-38f5-46a0-b5ec-6a24237c221b.png">

Screenshot with missing org link on deployments tab:
<img width="282" alt="Screen Shot 2021-08-09 at 4 02 42 PM" src="https://user-images.githubusercontent.com/15000375/128774212-a73ac9a6-640a-497e-bf4c-7500c7ef39fc.png">

**Comment by wass3r** [comment]
closed by https://github.com/go-vela/ui/pull/433
