### ISSUE TITLE
Repo settings page: no default selection for pipeline type

### ISSUE THREAD

**Issue by matt-fevold** [go-vela/community#357]
## Description

**For the latest RC**

repo settings page: "pipeline type" setting should probably have YAML selected as  default if it has not been set.

Example:
<img width="453" alt="Screen Shot 2021-08-09 at 4 06 01 PM" src="https://user-images.githubusercontent.com/15000375/128774530-9ea79348-8a72-48eb-8ea8-64b5b31a6a18.png">

**Comment by JordanSussman** [comment]
> repo settings page: "pipeline type" setting should probably have YAML selected as default if it has not been set

Have you updated the underlying database to default all existing repos to utilize the `pipeline_type` of `yaml`? Example SQL:

```sql
UPDATE repos
SET pipeline_type = 'yaml' 
WHERE pipeline_type IS NULL;
```

**Comment by wass3r** [comment]
indeed. that was not done in our test env :shame: 🙇🏼
