### ISSUE TITLE
add pipeline_type to v0.9 migration

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#359]
1. add alter statement for `pipeline_type` column
1. add update statement for `pipeline_type` column
---
> repo settings page: "pipeline type" setting should probably have YAML selected as default if it has not been set

Have you updated the underlying database to default all existing repos to utilize the `pipeline_type` of `yaml`? Example SQL:

```sql
UPDATE repos
SET pipeline_type = 'yaml' 
WHERE pipeline_type IS NULL;
```

_Originally posted by @JordanSussman in https://github.com/go-vela/community/issues/357#issuecomment-895590240_

**Comment by KellyMerrick** [comment]
https://github.com/go-vela/community/pull/362

another pr will need to be created as part of the v0.9.0 release to update deps
