### ISSUE TITLE
Link a deployment back to a build in Vela

### ISSUE THREAD

**Issue by JayCeeJr** [go-vela/community#364]
## Description

When viewing deployments in vela, it would be great to provide a link to the build the deployment triggered. It would also be nice to display the latest successful deployment to each environment, which would be possible after creating the relationship between deployments and builds.

## Value

At a glance users would be able to see what deployment/build is deployed in each environment, and navigate between them.

## Definition of Done

Create the relationship between deployments and builds in the vela database. Provide this information in the api and display it in the UI.

## Effort  (Optional)

Effort would be significant, this will require changes to server, ui, and types repos, along with database changes.

## Impacted Personas (Optional)

Everyone

**Comment by JayCeeJr** [comment]
I used the element from the build page that shows the recent builds, in the deployments list. It shows the last 3 builds for the deployment, clicking on one will bring the user to the build, and hover shows some details.

<img width="1696" alt="Screen Shot 2021-08-18 at 2 29 20 PM" src="https://user-images.githubusercontent.com/1265665/129960283-bb02eb1a-d5a4-4edc-be2b-ef0f6e9aebd5.png">


<img width="1712" alt="Screen Shot 2021-08-18 at 2 29 31 PM" src="https://user-images.githubusercontent.com/1265665/129960293-a3789f8d-1b3e-45c7-a768-0eba678e9e33.png">

**Comment by plyr4** [comment]
completed via https://github.com/go-vela/server/pull/1031 
<img width="1649" alt="Screenshot 2024-09-19 at 9 06 35 AM" src="https://github.com/user-attachments/assets/57a6810d-bce8-4442-90d7-c81d5b67b322">
