### ISSUE TITLE
Comment event does not provide pull request branch name.

### ISSUE THREAD

**Issue by c-horn** [go-vela/community#384]
## Description

Have the value of a pull request branch's name available on any event created from that PR's context.

Currently when triggering builds off of a GHE PR comment the value available in the `BUILD_BRANCH` / `VELA_BUILD_BRANCH` environment variables is the target of the PR (`master` instead of `feature-x`, etc).

## Value

Our team would like to scope snapshot / dev builds and one-off deployments with the name of the feature branch to differentiate from vanilla "dev" or "staging".

## Definition of Done

Able to build on a PR comment an template names with something like `${PULL_REQUEST_BRANCH}` env or similar.

**Comment by susangreve** [comment]
Thanks for opening this issue. We've added it to the backlog and will assess priority

**Comment by c-horn** [comment]
For anyone interested in doing something similar a workaround I use now is `${VELA_PULL_REQUEST}` which is the ID of the PR and is included in the `issue_comment` payload, see:
https://go-vela.github.io/docs/reference/environment/variables/

**Comment by plyr4** [comment]
definitely doable! 
linking some code that might be a good starting spot
https://github.com/go-vela/server/blob/main/api/webhook/post.go#L352-L368
https://github.com/go-vela/types/blob/main/library/build.go#L143-L151
