### ISSUE TITLE
Show absolute timestamp on `Builds` list 

### ISSUE THREAD

**Issue by 10hendersonm** [go-vela/community#399]
## Description

It's difficult to correlate issues in builds looking into the past because `5 days ago` is both mentally harder to grok than and less deterministic than `2021-10-02T12:00:00+05`. I'd like if the build list showed absolute timestamps rather than (or in addition to) relative offsets.

![image](https://user-images.githubusercontent.com/14095644/136424811-2f9e6e88-1e47-4f3f-ba8c-e49c05020c20.png)

## Value

This makes it faster and easier to isolate when issues started occurring in old builds due to outside events (opensource/upstream changes, DNS, etc).

## Definition of Done

- Build list displays a timestamp.
- Stretch goal: User can select a preferred display timezone.
- Stretch stretch goal: User can select a preferred display time format.

## Effort  (Optional)

1 hour?
Stretch goals may be longer (2 days?).

## Impacted Personas (Optional)

Vela users may save a couple seconds but gain a good deal of accuracy when isolating issues.

**Comment by cognifloyd** [comment]
Another program I use, StackStorm, converts timestamps between local time and utc when you click on the timestamp. By convert I mean, clicking on one timestamp switches all the timestamps to the other mode. Maybe something similar could be used here.

Clock on one is the yesterdays, and then ask if the yesterdays are replaced with a precise timestamp.

**Comment by 10hendersonm** [comment]
Agh I just now realized the timestamps are `title`d onto the elements so they show on hover.

![image](https://user-images.githubusercontent.com/14095644/136610366-9e37e9e6-2e88-4639-9a0c-fd53a898ac58.png)

TBH this is probably all I need, I just didn't see it was there. 

Options, any of which I would be OK with:

- Leave it as is and close this
- Make it more obvious (a little icon or something showing hoverability)
- Something more full-featured (toggle, preference, etc)

**Comment by bmuenzenmeyer** [comment]
Implemented by some guy within https://github.com/go-vela/ui/pull/223

**Comment by susangreve** [comment]
This will be released with 0.12.0

**Comment by kaymckay** [comment]
https://github.com/go-vela/community/issues/446
