### ISSUE TITLE
Improve tracing/logging of components

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#419]
## Description

It should be easy to track issues between the server and worker by improving logs messages and/or adding tracing to the various sections of the codebase.

## Value

Ease troubleshooting when attempting to track down issues.

## Definition of Done

Administrators are able to track the lifecycle of a build with logs and/or tracing data.

## Impacted Personas (Optional)

Vela Administrators

**Comment by jbrockopp** [comment]
A PR has been opened for this:

https://github.com/go-vela/worker/pull/246

**Comment by jbrockopp** [comment]
A PR has been opened for this:

https://github.com/go-vela/server/pull/555

**Comment by jbrockopp** [comment]
Another PR has been opened for this:

https://github.com/go-vela/server/pull/557

**Comment by jbrockopp** [comment]
This is complete.
