### ISSUE TITLE
Add content for templates in vela-tutorials

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#42]
## Description

Original story: https://github.com/go-vela/vela-tutorials/issues/2

Add content for the [templates](https://github.com/go-vela/vela-tutorials/tree/master/templates) section.

## Value

Decrease barrier to entry with templates
Increase clarity around intended use-cases for templates
Create a guide for other organizations to create their own templates

## Definition of Done

The `tutorials` section of this repository contains content.

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

users who use templates

**Comment by plyr4** [comment]
theres plenty of content in 
https://go-vela.github.io/docs/templates/tutorials/ (could use more instances)
and https://go-vela.github.io/docs/tour/templates/
if we feel the need for more content, more concise issues would be appreciated and helpful

**Comment by plyr4** [comment]
as an aside, there _is_ a lot of additional content in go-vela/vela-tutorials that could be migrated to the doc-site, lets do that
