### ISSUE TITLE
improve worker api spec generation

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#433]
## Description

the worker spec currently has to be created manually and checked into source control. we should set it up similar to the server API where it gets generated in CI (GitHub Actions) as part of the release.

## Value

automatic worker API spec generation and validation.

## Definition of Done

API spec is removed from source control
GitHub Actions workflow is tweaked to include the generation and validation of the worker spec (see go-vela/server for an example)

## Impacted Personas (Optional)

Admins
Users

**Comment by KellyMerrick** [comment]
This has been implemented [here](https://github.com/go-vela/worker/actions/runs/7877697882/workflow#L30-L40). Please open another issue if you have other ideas.
