### ISSUE TITLE
Expose GitHub Tagger

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#436]
## Description

Along with BUILD_AUTHOR and BUILD_AUTHOR_EMAIL, I would like to see TAGGER and TAGGER_EMAIL exposed in vela.

## Value

When we run our release process (tag from github or from commandline), vela picks up the BUILD_AUTHOR, who was the last person to commit to master. They are then the "change owner" in the CR that gets created, not the person who is doing the tag (and thus the release).

**Comment by wass3r** [comment]
the field `VELA_BUILD_SENDER` is available and fills this need.
