### ISSUE TITLE
Improve CLI flag names

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#442]
## Description

With the change being introduced via https://github.com/go-vela/cli/pull/311, it would be opportune to comb through the commands and catch/fix any sort of stutter that might be more apparent as a result of the change. For example:

`vela view build --build 2`

## Value

No stutter in CLI commands
Fairly low hanging fruit to improve the CLI experience

## Definition of Done

All commands/flags have been reviewed and adjusted as needed

**Comment by KellyMerrick** [comment]
Closing this as complete. However, there may be other opportunities. Please open another issue with other specific examples as you come across them.
