### ISSUE TITLE
"Add Deployment" page - populate fields from query parameters

### ISSUE THREAD

**Issue by dan-kirberger** [go-vela/community#451]
## Description

We have some tooling that compares our apps in various environments, say tag `400` is in dev and `385` is in stage. We'd like to try using deployments to promote to stage.

Our options with that are:
1) Go to the "Add deployment" page to submit a request.
➕ : No dependencies
➖ : Must enter data manually, error prone.

2) Run a vela deploy command on the terminal.
➕ : We can programmatically generate the command that should be run in our tooling (like making sure the right parameters are provided)
➖ : Need vela cli installed, not something you typically normally need day to day, since the UI is so fancy. Takes you out of our slick web "dashboard" experience

What if the "Add deployment" page pre-populated fields based on query parameters?

![image](https://user-images.githubusercontent.com/16195927/144672354-6e22ac3b-abc0-4596-91dc-5a9c4fb5f236.png)

## Value

Minor engineer convenience for creating deployments.

## Definition of Done

Form fields pre-populate (including parameters) based on the query parameters on the page.

## Effort  (Optional)

~1 Day? Operating on query parameters on the page to pre-populate form, no API interaction

**Comment by dan-kirberger** [comment]
Github has similar functionality when creating a tag:
https://git.target.com/ORG/REPO/releases/new?tag=rc0.0.797

Will pre-populate the tag field with the provided value.

**Comment by plyr4** [comment]
not obvious, but this was completed in https://github.com/go-vela/ui/pull/761 and becomes more clear with https://github.com/go-vela/ui/pull/818 !
