### ISSUE TITLE
Add environment variable to limit sourceable repos to a specific user/organization

### ISSUE THREAD

**Issue by tmapes** [go-vela/community#472]
## Description
Build off of [VELA_REPO_ALLOWLIST](https://github.com/go-vela/server/blob/v0.11.0/cmd/vela-server/main.go#L78) to be less specific, but given a comma separate list of account name or organization names that are allowed to be activate on Vela.

Drone currently offers this via [DRONE_REPOSITORY_FILTER](https://docs.drone.io/server/reference/drone-repository-filter/)

## Value
Useful for users who want to enable their entire account and block anything else.
Having a user filter (over a repo filter) allows those user(s) to add/remove any number of repos without needing to reconfigure and restart their Vela instance.

## Definition of Done
Done when a new configuration flag / environment variable is added that allows the administrator to set a list of users/orgs that are able to be enabled on.

**Comment by wass3r** [comment]
👋🏼 we talked about this feature elsewhere. i forgot what the code looks like that checks the allow list, but based on https://github.com/go-vela/server/blob/v0.11.0/api/repo.go#L957, i think the use-case you are looking for is supported?

**Comment by tmapes** [comment]
> 👋🏼 we talked about this feature elsewhere. i forgot what the code looks like that checks the allow list, but based on https://github.com/go-vela/server/blob/v0.11.0/api/repo.go#L957, i think the use-case you are looking for is supported?

Ah I so I can just do `tmapes/*`! Very nice. I think this issue can be closed then.

**Comment by wass3r** [comment]
I'll close for now. We can reopen if you encounter an issue with it. 👍🏼

**Comment by tmapes** [comment]
The current implementation of this environment variable works with the below configuration to limit to a single user/org.
```
"VELA_REPO_ALLOWLIST=tmapes/*"
```
I do not see any reasons as of now to reopen this.
