### ISSUE TITLE
fix flakiness of CLI release assets in CI

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#491]
## Description

The go-vela/cli project continues to exhibit flakiness for releases, often resulting in multiple attempts to successfully release the assets. Explore ways to fix the release process for the CLI.

## Value

Consisent, reliable release process for the CLI project

## Definition of Done

Implement changes to the release process that improve consistency. Ideally, in a normal scenario there shouldn't be any retries needed to release the assets.

## Impacted Personas (Optional)

Project Maintainers

**Comment by KellyMerrick** [comment]
This seems to be better on its own, but we can monitor to confirm if this is the case or if we need to do work.

**Comment by wass3r** [comment]
i'll close for now
