### ISSUE TITLE
Update to Go 1.18

### ISSUE THREAD

**Issue by kneal** [go-vela/community#501]
## Description

The new Go version is coming out soon and we should update after the first minor patch has been released. Additionally, there are some formatting changes to encourage people to use `any` instead of `interface{}`. We should try and get a new linter added to check for that in the Go files. 

## Value

Helps use get the latest and greatest security/feature updates and will help our code look like the community expectations. 

## Definition of Done

- all Go repos have been updated to 1.18.x
- linter has a check for `interface{}` to `any` (if it exists of course)

**Comment by wass3r** [comment]
additionally, we might be benefit from utilizing `runtime/debug.ReadBuildInfo` and maybe some of the new `strings` functions.

ref: https://tip.golang.org/doc/go1.18

**Comment by kneal** [comment]
The fuzzing being in the STL code be useful in compiler as well. I think that would take some research and implantation experimentation tho.

**Comment by wass3r** [comment]
relevant: https://github.com/golangci/golangci-lint/issues/2649

**Comment by wass3r** [comment]
we are on 1.19+
