### ISSUE TITLE
Support projektor links in output

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#528]
## Description

Turn links to Projektor reports into `<a href=...>` tags so they are click-able.

## Value

There are quite a few teams using Projektor to view test failure output in their builds across our company, so this seems like a nice time saver.

**Comment by wass3r** [comment]
for reference: https://github.com/craigatk/projektor

**Comment by wass3r** [comment]
@colindean yes, we've been talking on the side on something along those lines. allow some kind of structured output that the UI can pick up and display. i don't think it's too premature :)

**Comment by plyr4** [comment]
the ui processes weblinks now!
