### ISSUE TITLE
Add comment event to builds page event filter

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#53]
## Description

Currently the filter on the builds page doesn't account for `comment` events.

## Value

Allow users to filter by all currently supported events.

## Definition of Done

User is able to filter builds by selecting "comment" in the filter control.

**Comment by KellyMerrick** [comment]
https://github.com/go-vela/ui/pull/222

**Comment by KellyMerrick** [comment]
This will be available in the ui in the next release, date TBD.
