### ISSUE TITLE
Support CRON/scheduled jobs

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#538]
## Description

Support for CRON jobs

## Value

Our particular use cases may differ from others, but having the ability to schedule recurring jobs would greatly benefit our deployment of various tooling that supports development of our app. Some examples:
- we have a number of test automation suites to check service behavior that the app is dependent on and need to have the ability to schedule recurring builds of these suites
- our program authenticates with Apple services when deployed, but in order to work properly, it needs to be redeployed when its auth token expires (which Apple has set to occur every 8 hours). We're currently investing a lot of time in workaround discovery on this problem and while we think that it may be possible to get a token with a longer TTL, we know that we'll still need to redeploy every _n_ number of days anyway.

**Comment by Derekt2** [comment]
Another example I'd like to highlight is when a repo uses a large number of external dependencies, especially when built from source code external repositories. Being able to schedule rebuilds to test their latest versions is helpful to ensure we're getting the latest version of a repository.

**Comment by JordanSussman** [comment]
We are planning to submit a proposal for this functionality in the near future.
