### ISSUE TITLE
Allow local pipeline execution

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#54]
## Description

Enable the ability to execute a Vela pipeline on a local workstation

## Value

* provide another mechanism to troubleshoot Vela pipelines
* reduce dependency on Vela services being available to execute pipelines
* maintain feature parity with existing CI solutions

## Definition of Done

A Vela pipeline can be ran on a local workstation

## Effort  (Optional)

2 weeks

## Impacted Personas (Optional)

everyone

**Comment by kneal** [comment]
_Overall Goals_

- [ ] Add a `local` executor to [go-vela/pkg-executor](https://github.com/go-vela/pkg-executor)
  - Utilize `docker` runtime from [go-vela/pkg-runtime](https://github.com/go-vela/pkg-runtime)
- [ ] Create a new CLI command for [go-vela/cli](https://github.com/go-vela/cli) to run `local` executor. Ideas:
  - `vela exec`
  - `vela run`
  - `vela pipeline exec`
  - `vela pipeline run`
- [ ] Begin exhaustive testing for new CLI command to run `local executor`
  - How do `secrets` work?
  - How do `services` work?
  - How do `stages` work?
  - How do `steps` work?
  - How do `templates` work?
  - Should the command clone the repo for you?
  - Or should it be expected to be running inside the repo with the pipeline?
- [ ] Provide documentation for consumers on local executor
