### ISSUE TITLE
Improve configuration file error handling and prevention workflow and tooling

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#541]
## Description

A new Vela build I’m doing up wasn't showing up in Vela. I couldn't find a way to tell what's wrong from the Vela side, because when I pushed, GitHub would emit an event because the hook is configured and Vela is configured to listen for that particular event (push/pr). 

When I looked at the webhook logs in GitHub, I saw this as the response:

```json
{
  "error": "unable to process webhook: failed to compile pipeline configuration for org/repo: unable to unmarshal yaml: unable to unmarshal into StringSliceMap"
}
``` 

This was confusing. I was not sure what's wrong. The error doesn't allude how to fix that's wrong, either.

After some thrashing, I figured it out. What ended up being the problem was this:

```yaml
steps:
- name: blah
  image: blah/blah
  environment:
  - OOPS: "Can't put an array in this context"

```

It’d be nice to have a clearer way of figuring out that my build config wasn’t valid from with Vela instead of having to look at Github’s hook logs. Vela should be able to tell me _in Vela_ that it received an event but wasn't able to act because the configuration was invalid.

It’d also be nice to have that error be more helpful when the environment contains something invalid in its context, so type checking perhaps at the JSON level. 

## Value

It is onerous to inspect webhook looks to determine configuration file issues.

**Comment by KellyMerrick** [comment]
Hook errors are now available via the Audit tab in Vela.
