### ISSUE TITLE
Change Default Value of "CI" Environment Variable

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#554]
## Description

Would it be possible to update Vela to set the environment variable `CI` to `true` instead of `vela`? It seems most industry tooling is built around `CI` being a boolean-like and it’s what’s set by all the CI tools I could find in the wild:
- https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
- https://www.appveyor.com/docs/environment-variables/
- https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
- https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops#predefined-variables
- https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference
- https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
- https://docs.drone.io/pipeline/environment/reference/ci/

## Value

This helps ensure that Vela works well with industry tooling that expects the `CI` variable to be a boolean-like. A recent example is an update to `Pipenv` that expects the value to be boolean-like otherwise an exception is thrown.

**Comment by dtanner** [comment]
https://github.com/go-vela/docs/pull/293
https://github.com/go-vela/server/pull/619

**Comment by amystamm** [comment]
Reminder @dtanner merge docs in with release
