### ISSUE TITLE
Allow terminating a running build

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#56]
## Description

Enable canceling/stopping a running build.

## Value

* prevent a misconfigured or long running build from harming the environment
* maintain feature parity with existing CI solutions

## Definition of Done

A user has a mechanism to cancel/stop a running build

## Effort  (Optional)

1 week

## Impacted Personas (Optional)

everyone

**Comment by meinenec** [comment]
resolved by https://github.com/go-vela/server/pull/235
