### ISSUE TITLE
Allow mapping of build steps to github statuses

### ISSUE THREAD

**Issue by dan-kirberger** [go-vela/community#576]
## Description
It's handy to have multiple github statuses to track parts of your build (say, one for the lint step, one for build, one for automated tests, etc).

It's a bit clumsy setting that up in Vela currently, as we have to explicitly send github statuses before and after each step we care about.

Would it be possible to handle more of that for us?

Say:
```
- name: lint
  image: some-node-image
  context: Linting
  commands:
    - yarn lint
```

With the above `context` field above, it will manage a "Linting" status on github, viewable from the pull request:
![image](https://user-images.githubusercontent.com/16195927/165607090-f7f5113c-338c-4af2-9d96-fe001749b5db.png)

When this exists, it would automatically set the status to "pending" for all contexts when a build starts, and update to success/failure as necessary. In addition, the link provided in the github status would be a link to that specific build step in vela.

## Value

Its very handy to view a PR at a glance and see which steps passed/failed, with direct links to the steps in question.

**Comment by cognifloyd** [comment]
That's a cool idea. I don't know about reporting at a step level, but I can see using something like this for each stage.

I'm not sure `context` clearly describes what this does, so another keyword might be better. What about `report:`? That doesn't seem to fit as well either, hmm. I'll have to noodle some more on it.

**Comment by dan-kirberger** [comment]
Yeah good call. "Context" is the name of it on the GitHub status api but you're right, it is a bit too vague here.

Stage would work too!

**Comment by wass3r** [comment]
maybe it's a boolean and takes on the name of the step as the "context"? that way you can't cause confusion by naming it "linting" when it actually happened on a step called "push-to-prod"?

**Comment by wass3r** [comment]
also a little worried about potential for api abuse 🤔
