### ISSUE TITLE
remove byte-chunks from log streaming

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#577]
## Description

(placeholder for now - might add more detail later)

Remove byte-chunks log streaming functionality from executor/worker.

## Value

reduce tech debt and allow for enhancements that might be hindered by some side-effects of byte-chunks implementation.

## Definition of Done

byte-chunks is removed from code base

**Comment by cognifloyd** [comment]
time-chunks works better for me. I'm cool with removing byte-chunks.

**Comment by wass3r** [comment]
fixed via https://github.com/go-vela/worker/pull/447
