### ISSUE TITLE
Provide exact build timestamp for UI

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#58]
## Description

Currently, the timestamp for a build is provided in a "humanized" form.

i.e.

* `1 day ago`
* `8 hours ago`
* `25 minutes ago`

There is a desire to provide an accurate timestamp to the second for troubleshooting purposes.

## Value

* improve troubleshooting experience with the UI
* maintain feature parity with existing CI solutions

## Definition of Done

A mechanism exists for a user to capture the exact timestamp a build was ran via the UI

## Effort  (Optional)

1 day

## Impacted Personas (Optional)

everyone

**Comment by bmuenzenmeyer** [comment]
I'd like to take a stab at this.
