### ISSUE TITLE
Enhance graceful worker shutdown functionality

### ISSUE THREAD

**Issue by amystamm** [go-vela/community#581]
## Description

Disable a worker on all the machines without actually taking them down

Add functionality for worker to stop listening to the queue

Add a status of each worker? We have the data, can we get it displayed nicely?

**Comment by wass3r** [comment]
i think the problem should be redefined. the functionality works as expected - for the most part. once SIGTERM is issued, the worker does indeed finish the current build and stop listening to the queue. there is at least one area of improvement, in that, depending on timing, once the SIGTERM signal is sent, the worker will wait for the checkin loop (15m by default) to complete before _not listening_ anymore.
