### ISSUE TITLE
Spike: Investigate platform admin page in UI

### ISSUE THREAD

**Issue by amystamm** [go-vela/community#582]
## Description

Design Session!
Add worker data as referenced in https://github.com/go-vela/community/issues/581
Gather usability data from platform admins
Get all Vela committers involved
Health data for connected components (DB connectivity, queue size, etc) 
Utilize our existing Grafana dashboards and see if there are valuable stats we can integrate

**Comment by cognifloyd** [comment]
So, thinking this through it sounds like a progression of features to add in this admin page:
- monitoring worker status (how many workers, what builds they're managing, what queues it has subscribed to, what executor/runtime it uses)
    - might involve some kind of event streaming so the UI can worker state changes as they happen
- worker maintenance functions (stop accepting builds, shutdown worker)
- worker config (change configured queues for workers, ...)

Longer term possibilities:
- pluggable way to create new workers (fire off a vela build, send a webhook to an external system, ...)
- pluggable config for executors / runtimes
    - kubernetes runtime has some more complex things that could be nice to be configurable like the PodsPipelinesTemplate (which includes things like default pod labels, resource limits, dns config, ..., but would involve changing a resource in kubernetes)

**Comment by jbrockopp** [comment]
DB integration for the admin page:

* see database statistics

To start, perhaps we show a list of the tables in the DB and the size of those tables?

The idea would be to show a very minimal amount of info and make changes based off feedback/ideas

* enable "fixed" database operations

Too many times I've had to run a DB query that wipes old/stale pending and running builds

I don't to propose a raw SQL query console, but perhaps allow wiping pending/running builds older than a fixed date?

Perhaps the user provides a timeframe from a drop down? or calendar? and Vela takes that and runs a "fixed" SQL query

**Comment by chrispdriscoll** [comment]
Sounds like Amy might have a list of User Stories coming out of this SPIKE. I'll connect with her when she returns to get that list and create the necessary stories.

**Comment by chrispdriscoll** [comment]
Per Amy...I don’t have anything outside of what is already in GitHub issues #548, 549, 550, 551 and 552 on the internal board. 
 
Here are the notes that I had from the initial discussion:
 
Persona: Platform admin
 
 Persona: Non-Platform Admin
Org Admin
Repo Admin
Anonymous user
"Regular" user
 
 
These are the actions that the team decided were the most important and wanted to do first:
Admin:
Create a view for a platform admin to see our workers
Take action on Workers
Shutdown
Reboot
Non-Admin:
Ability to view workers, but not take action
Summary view - give users more info on workers  - consideration: making requests and adding load to have everyone view this info
Ability to see where their build is in the queue
Ability to see # of busy workers vs total workers
 
 
This is the list from our brainstorming session of all the other functionality they would like to see:
are all workers up?
            are workers accepting builds?
            validating configuration on workers
            validating os level system information
            validating kernel level information
            what is that worker doing? (Build, rebooting, waiting)
            give link to current build
            container and system process usage (how much memory did a build have access to?)
            showing and updating build_limit
            worker size, specs,
            mass enable/disable workers
            vacuum database
            too many links to random places (dynamic place for useful stuff that we use)
           
    
        workers:   
        routine operations 
            - disable queue
            - reboot, shutdown, (vm)
            - build_limit
            - service cleanup
            - disk operations
            - fetch running system services
            - docker level operations?
                - docker prune (cleanup)
                - fetch docker information
            - last_check_in comparison + warning
            - last run job
            - current running job time
            - queue length per worker
            - success/failure per worker
            - routes + build pinned to worker
            - saturation (how often is this worker performing work)
            - pinning and builds ran metrics
            - managing routes (add/remove dynamic routes)
            - provisioning or adding a worker (mute)

**Comment by ecrupper** [comment]
Platform admin page is available as of `v0.24`. Any requests for features/enhancements to that page should open a new issue. Marking as closed
