### ISSUE TITLE
Create Plugin release process

### ISSUE THREAD

**Issue by amystamm** [go-vela/community#583]
## Description

Determine how we release plugins
- cadence
- how this fits in with our regular release cadence
- prioritize plugins to release

**Comment by wass3r** [comment]
going to pull in https://github.com/go-vela/community/issues/603 into this one, since this is something that should happen for all plugins as part of a cadence.

**Comment by ecrupper** [comment]
Update quarterly is where we are landing on this. Feel free to open new issue if we want to change that or add anything.
