### ISSUE TITLE
Upgrade vela-s3-cache

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#620]
## Description

vela-s3-cache
v0.5.1 (latest) Apr 9, 2021
https://github.com/go-vela/vela-s3-cache 

## Security Findings

Findings 10,928

Latest: 1,837 (216 Critical, 1,621 High)
v0.4.0: 1,700
v0.3.0: 882
v0.2.0: 1,541
v0.1.0: 2,047
unknown: 2,922

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-s3-cache/releases/tag/v0.6.0
