### ISSUE TITLE
Upgrade vela-npm

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#621]
## Description

vela-npm
No releases published
https://github.com/go-vela/vela-npm

## Security Findings

870 (150 Critical, 720 High)

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
waiting for https://github.com/go-vela/vela-npm/pull/32
and https://github.com/go-vela/vela-npm/pull/31

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-npm/releases/tag/v0.1.0
