### ISSUE TITLE
Upgrade vela-slack

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#622]
## Description

vela-slack
v0.2.0 (lastest) Nov 12, 2021
https://github.com/go-vela/vela-slack

## Security Findings

Findings: 555

Latest: 12 (2 Critical, 10 High)
v2.4.0: 60
unknown: 483

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-slack/releases/tag/v0.3.0
