### ISSUE TITLE
Update vela-docker

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#624]
## Description

vela-docker
v0.6.0 (latest) Nov 11, 2021
https://github.com/go-vela/vela-docker

## Security Findings

Findings: 1,811

Latest: 185 (20 Critical, 165 High)
v0.5.1: 1,595
f5703e3d: 31

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-docker/releases/tag/v0.7.1 released
