### ISSUE TITLE
Upgrade vela-git

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#625]
## Description

vela-git
v0.5.1 (latest) Feb 1, 2022
https://github.com/go-vela/vela-git

## Security Findings

Findings: 314

Latest: 42 (18 Critical, 24 High)
unknown: 272

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-git/releases/tag/v0.6.0 released
