### ISSUE TITLE
Upgrade vela-terraform

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#626]
## Description

vela-terraform
v0.4.1 (latest) July 22, 2021
https://github.com/go-vela/vela-terraform

## Security Findings

Findings: 924

Latest: 924 (147 Critical, 777 High)

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
waiting for https://github.com/go-vela/vela-terraform/pull/126

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-terraform/releases/tag/v0.5.0
