### ISSUE TITLE
Upgrade vela-ansible

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#627]
## Description

vela-ansible
v0.1.0 (latest) Mar 14, 2022
https://github.com/go-vela/vela-ansible

## Security Findings

Findings: 77

22fa12b2: 77 (19 Critical, 58 High)

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-ansible/releases/tag/v0.2.0
