### ISSUE TITLE
Upgrade vela-artifactory

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#628]
## Description

vela-artifactory
v0.4.0 (latest) Oct 29, 2021
https://github.com/go-vela/vela-artifactory

## Security Findings

Findings: 482

Latest: 13 (2 Critical, 11 High)
v0.3.0: 147
v0.2.0: 184
v0.1.0: 92
unknown: 46

## Definition of Done

[] plug-in updates resolve CVEs
[] plug-in updated and available for all teams

**Comment by wass3r** [comment]
https://github.com/go-vela/vela-artifactory/releases/tag/v0.5.0
