### ISSUE TITLE
List stages blocking a stage

### ISSUE THREAD

**Issue by colindean** [go-vela/community#640]
## Description

When I look at my running job, I want to know why a stage isn't running. It's probably because it's awaiting the completion of another stage. I want the job page UI to show what stages a stage depends on.

## Value

Primarily, because stages listed in `needs` seemingly aren't validated, misconfiguration can be expensive. Listing dependent stages with some status could help surface this more quickly while also showing a semblance of a DAG of stages.

* ⌛ Waiting for the dependent stage to complete
* 🟢 Dependent stage complete
* 🔴 Dependent stage errored
* ❔ Dependent stage not found in configuration

## Definition of Done

The stage header, e.g. `docker-build-promote server`, will have its dependent stages listed:

```
[docker-build-promote server]
waiting on dependent stages: 🟢 checkout 🟢 lint ⌛ build ❔doesnotexist
```

**Comment by plyr4** [comment]
would you consider this completed with the introduction of the build visualizer?
https://github.com/go-vela/community/issues/71#issuecomment-1746934522

**Comment by ecrupper** [comment]
Visualizer addresses this, so I will close.
