### ISSUE TITLE
server: pull request edits are triggering malformed builds

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#650]
## Description

pull requests with "action:edited" are triggering builds that do not meet the default opened/synchronized actions. 

## Additional Information

functionality brought in with these changes:
https://github.com/go-vela/server/pull/630
https://github.com/go-vela/types/pull/251

**Comment by ecrupper** [comment]
Fixed in [v0.14.3](https://github.com/go-vela/server/releases/tag/v0.14.3)
