### ISSUE TITLE
Allow skipping a build for a specific commit

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#66]
## Description

Enable the ability to skip triggering a build for a repo if the commit message contains a special set of characters in the commit message.

Exploration and research will be necessary to understand what syntax we will support for the commit message that invokes this functionality.

## Value

* reduce load on Vela systems by skipping the execution of an unnecessary build
* maintain feature parity with existing CI solutions

## Definition of Done

A specific pattern in the commit message will instruct Vela to skip triggering a build for that event.

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

everyone

**Comment by bmuenzenmeyer** [comment]
we are running into this issue - and need to code around it. hoping for a solution with drone parity soon.
thanks!

**Comment by 10hendersonm** [comment]
> we are running into this issue - and need to code around it. hoping for a solution with drone parity soon.
> thanks!

Echoing @bmuenzenmeyer  - I'm having difficulty coming up with a Vela-only approach to this, so I'll be writing environment checks into our tooling instead.
