### ISSUE TITLE
Release Story 1: cut v0.15.0-rc1

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#663]
## Release Story 1: cut v0.15.0-rc1
External

## Timing
Can be concurrent with stories 2 and 3

## Background
This cuts the go-vela external (pre-release) rc1 
https://github.com/go-vela/server/releases (similar for types, sdk-go, worker, cli, ui)
fyi, ui can be released separately, so is currently n+1 version (server 14, ui 15)

**Comment by plyr4** [comment]
upgrading go-vela server to Go v1.19 https://github.com/go-vela/server/pull/690

**Comment by wass3r** [comment]
all core repos have been bumped to 1.19 of Go.

`types` has been tagged with v0.15.0-rc1 last week.
`server` https://github.com/go-vela/server/pull/703 (after which it will get tagged with the same)

**Comment by wass3r** [comment]
all core repos have been tagged with v0.15.0-rc1
