### ISSUE TITLE
Release Story 2: prep draft pr for release notes

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#664]
## Release Story 2: prep draft pr for release notes
External

## Timing
Can be concurrent with stories 1 and 3

## Background
pr sometimes combined with migration tool, but could still be separate story
https://github.com/go-vela/community/pull/591

**Comment by wass3r** [comment]
https://github.com/go-vela/community/pull/691 created

i might add in a word or two about default branch switch and Go 1.19 bump across the board
