### ISSUE TITLE
Release Story 3: prep draft pr for migration tool

### ISSUE THREAD

**Issue by chrispdriscoll** [go-vela/community#665]
## Release Story 3: prep draft pr for migration tool
External

## Timing
Can be concurrent with stories 1 and 2

## Background
pr sometimes combined with release notes, but could still be separate story
migration tool often necessary for database changes
simple, if there is no migration tool necessary for this release like https://github.com/go-vela/community/pull/439 (fyi, this one combined with release notes)
more involved, if there is a migration tool like https://github.com/go-vela/community/pull/592

**Comment by wass3r** [comment]
not needed for this release
