### ISSUE TITLE
enhance(ui): add date + time to deployments 

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#677]
## Description

would be useful to see the date + time in the deployments tab.

this is just a rough example, see the "17 minutes ago":

<img width="1446" alt="Screen Shot 2022-09-09 at 10 07 29 AM" src="https://user-images.githubusercontent.com/48764154/189382791-87591682-0ab9-4326-b2f6-a92a56071316.png">

that could be exact time, relative time, doesnt really matter

## Value

usability + improved experience

## Definition of Done

users can see when deployments were processed by vela

## Effort  (Optional)

couple days, would most likely require modification to the deployments database schema to include the timestamp, then the ui work to render it 

## Impacted Personas (Optional)

users

**Comment by wass3r** [comment]
is this an extension of the timestamps that @kaymckay added for builds? or are you thinking something different for this scenario?

**Comment by plyr4** [comment]
yeah basically what the screenshot shows, which is an actual timestamp for the vela deployment object (doesnt exist right now)

**Comment by plyr4** [comment]
this was completed at some point when we revamped deployments
<img width="1653" alt="Screenshot 2024-03-19 at 5 41 43 PM" src="https://github.com/go-vela/community/assets/48764154/3cc3851b-1347-4fb6-b68b-74a221201783">
