### ISSUE TITLE
handle pull request events properly

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#678]
## Description
we turned off some functionality in https://github.com/go-vela/server/pull/677 for the time being. the link contains comments on what might be needed to turn this back on. just creating a story to make sure we don't lose track of it.

## Value

pull request event subscription works as expected

## Useful Information

see linked PR

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?

**Comment by ecrupper** [comment]
Handled properly with granular allow_events
