### ISSUE TITLE
Add pipeline visualizations

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/community#71]
## Description

We should add the ability to "visualize" a pipeilne via some type of dashboard and/or graph(s).

This should include the ability to see the order of execution of a pipeline and be distinct when visualizing `stages`, `steps` and `services`.

There are already a few different tools out there that have this concept:

* https://concourse-ci.org/
* https://www.gocd.org/
* https://www.jenkins.io/projects/blueocean/

## Value

* improve user experience when viewing a pipeline
* enhance ability to troubleshoot a running pipeline
* maintain feature parity with existing CI solutions

## Definition of Done

A user has some mechanism via the UI to visualize a pipeline

## Effort  (Optional)

2 weeks

## Impacted Personas (Optional)

everyone

**Comment by davidvader** [comment]
potential libraries:
- [d3-dag/d3](https://github.com/erikbrinkman/d3-dag) - this is the spiritual successor of d3-dagre but it just extends [d3](https://d3js.org/) with additional dag algorithms. this one is promising, and might work well but any layout library combined with `d3` will require a lot of manual code to configure the layout and html.
- [elm-visualization](https://package.elm-lang.org/packages/gampleman/elm-visualization/latest/) - pure elm graph visualizations, it includes force directed graphs. however, like d3, it requires you to create the layout yourself which is a lot of code. the core of the library is just an in-complete d3, which makes it hard to justify not just porting to a more capable library.
- [d3-dagre](https://github.com/dagrejs/dagre-d3) - not going with this one because it is officially deprecated, but it is one of the leading solutions still out there
- [WebCola/cola.js](https://github.com/tgdwyer/WebCola) - this one looks very promising, with support for hierchal grouping of nodes, and force DAGs, open source and maintained. its an interface to d3, much like the others.

**Comment by davidvader** [comment]
so far I've experimented with [d3-dagre](https://github.com/dagrejs/dagre-d3), [d3-dag/d3](https://github.com/erikbrinkman/d3-dag) and [elm-visualization](https://package.elm-lang.org/packages/gampleman/elm-visualization/latest/).

next up is [cola.js](https://github.com/tgdwyer/WebCola)

**Comment by davidvader** [comment]
after consideration i feel this might be better off as a spike.
the work will have to be broken down into several smaller efforts that can be performed by the server and the ui. a few that i can think of include:
- converting the data from the database to a format that can be consumed by a graph layout library
- consume the formatted data using a graph layout library like graphviz/viz.js, DOT, d3-dag, dagre, by-hand (ouch), etc to produce a layout
- render the graph layout using a visualization library like d3, elm-visualization, WebCola/cola.js, by-hand (no way), etc.

**Comment by davidvader** [comment]
some resources:
- [graphviz DOT guide](https://www.graphviz.org/pdf/dotguide.pdf)

**Comment by 10hendersonm** [comment]
[Mermaid charts](https://mermaid-js.github.io/mermaid/#/) might be another thing to look into.

**Comment by davidvader** [comment]
@10hendersonm oh awesome! i hadnt come across mermaidjs. the syntax reminds me of DOT but i like the direct js integration.
mermaid also looks like it uses 2 of the libraries ive been playing around with, under Credits:
> Many thanks to the d3 and dagre-d3 projects for providing the graphical layout and drawing libraries!

one drawback to dagre-d3 was the lack of an active maintainer, i wonder if mermaid forked the library

**Comment by davidvader** [comment]
note: the [go-graphviz](https://github.com/goccy/go-graphviz) requires c integration (CGO_ENABLED) which is an overhead dependency I would like to avoid.
its possible to use graphviz DOT generation on the client-side but at that point you may as well use a rendering library that is more robust like d3

**Comment by davidvader** [comment]
[d3-dag](https://github.com/erikbrinkman/d3-dag) has been proving to be successful in generating numerous layouts like sugiyama. feeding the layout into d3 to render the nodes has been successful but the graph that is produced for more complex pipelines is pretty messy. IE, more nodes, the worse it looks.
it makes me consider implementing a sugiyama/topological layout by hand (which i really dont want to do) and then passing that into d3.
more responsibility on us but we could control the granularity on node ranking, and we could do more complex rendering like clustered graphs (render the steps within a stage, for example) and services.

**Comment by plyr4** [comment]
d3-dag was actually not as flexible as I was hoping, mostly with no support for node size, layer spacing or vertical node size growth without using `arquint` layout which was depracated from the library a few releases ago.

DOT is proving to be much more reliable.
my previous assumption about graphiz support being dependent on CGO was only partially correct. we could use this [Go DOT](https://github.com/emicklei/dot) helper library to write up the graph, or write up the DOT graph string using the [Elm Graph.DOT](https://package.elm-lang.org/packages/elm-community/graph/latest/Graph.DOT) implementation.

IMO it makes sense in the client.

**Comment by wass3r** [comment]
i'm partial to d3 myself for the flexibility.

are we sacrificing anything in terms of interactivity going down the DOT path? (the story doesn't have it as a requirement, but that is something to consider, maybe)

**Comment by plyr4** [comment]
just picked this back up, sorry for the late response. 
but yes and no, DOT allows the limited use of `<table>` from [graphviz](https://graphviz.org/Gallery/gradient/table.html), which auto-sizes the nodes which is really nice. though it seems like not _everything_ is supported when you pass it through d3.draw :( for example, i can only assign an `id` to a `<td>` if i also attach an `href` 🤷 

and for interactivity, clicking etc, we just have to get creative and use d3 to select elements and add interactivity to them manually, but that would be true regardless of any layout algorithm we use with d3, we would need to add interactivity via d3.select anyways.

**Comment by plyr4** [comment]
so far the most annoying part has been dealing with transferring untyped data between d3, elm, and back, to control node expansions. still working on a better pattern, but so far the best ive been able to do is embed data inside `<table>` using `xlink:title`

**Comment by plyr4** [comment]
the biggest roadblock so far has been trying to find a solution for compiling graphviz in the browser that doesnt include modifying the UI's content security policies.

but thus far, this is the only way I can see it working is adding `script-src: unsafe-eval` and `style-src: unsafe-inline`.

https://github.com/go-vela/ui/commit/87d116a36cc0d794aca56450eacb23969655a174

**Comment by plyr4** [comment]
turns out `script-src: wasm-unsafe-eval` exists, and it seems to work for firefox chrome and safari.

this is far better than simply enabled `unsafe-eval` because from what i can tell theres no way for a user to remote-execute wasm code. and albeit extremely unlikely. 

still looking into how we can avoid `style-src: unsafe-inline` because from what i can tell, its not _actually_ needed, so i think im mis-using d3 styling.

**Comment by plyr4** [comment]
# demo 10/4/23

https://github.com/go-vela/community/assets/48764154/a1eb4042-9c5a-4c37-ac89-5a1ee07af3bf

**Comment by plyr4** [comment]
this is complete, im looking forward to any bugs or suggestions people find! :) please let me know if something doesnt seem right
