### ISSUE TITLE
Improve maintainability of source code files

### ISSUE THREAD

**Issue by bmuenzenmeyer** [go-vela/community#747]
## Description

Clean up source code files throughout Vela to make them more maintainable.

## Value

Reduce future notification noise and maintenance cost

## Definition of Done

I don't know the product very intimately, but I guessed at a scope:

> Citing PRs like this one: https://github.com/go-vela/types-private/pull/4/files/26402fd670272d401ea48e912e2bd234cf8de034

- [x] Team to decide on course of action. I worked with Legal to clarify:

- Including a copyright notice with file each is **not required**
- The year in the notice specifies the **year of first publication**. So there is no need to go back and update the year in existing files.
    - ✅ For example, for a project that began in 2022, this suffices: `© 2022 Target Brands, Inc.`
    - ❌ No need to update this each year:
      ```diff
      - © 2022 Target Brands, Inc.
      + © 2023 Target Brands, Inc.
      ```
    - ❌ No need to specify a range: © 2022 - present Target Brands, Inc.
- Do not specify `Copyright (c)`, this is redundant.

- [x] Once an option is chosen (remove completely, update each file to state the year created only), change all files. 
- [x] Address any linting or automation checking for current year.

**Comment by wass3r** [comment]
we'll go with the option to remove the copyright piece from the source files. i'll open an example PR to a repo of what the change will look like for each repo.

**Comment by bmuenzenmeyer** [comment]
I wonder if it could be automated

**Comment by wass3r** [comment]
oh yes. it will be. i just want to make sure i understand what the change will look like.

in fact. i'm wondering about replacing our standard three-liner in our code files:
```
// Copyright (c) 2022 Target Brands, Inc. All rights reserved.
//
// Use of this source code is governed by the LICENSE file in this repository.
```
with a SPDX identifier, such as:
```
// SPDX-License-Identifier: Apache-2.0
```

more info: https://spdx.dev/ids/#why

In our README's in the repos, also looking to reduce:
```
## Copyright and License

Copyright (c) 2022 Target Brands, Inc.

[Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0)
```
to just:
```
[Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0)
```

do you see any issues with the above?

**Comment by bmuenzenmeyer** [comment]
The README I am less sure of (and since there is only one it doesn't matter as much to me), but I like the file name change

**Comment by wass3r** [comment]
Here's an example of the changes I was thinking to make: https://github.com/go-vela/vela-email/pull/41.

couple of callouts:
1. https://github.com/go-vela/vela-email/pull/41/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R189 follows guidance here more closely: https://www.apache.org/licenses/LICENSE-2.0.html#apply. one contention might be the year i picked. was hoping to keep this the same across all repos, but it may differ per repo, depending on what it _needs_ to be.
2. curious on thoughts for https://github.com/go-vela/vela-email/pull/41/files#diff-70d86781add4b013df40d3433bf0ed8033639b5e05fcc2c43d23afe0085d4892R37. took some liberties here maybe, but saw another module do this.

the remainder of the changes are pretty uncontroversial, i think.
