### ISSUE TITLE
vela login segfaults and dumps a stack trace after asking for login information when the server cannot be found

### ISSUE THREAD

**Issue by colindean** [go-vela/community#76]
## Description

I installed the vela client and attempted to login. I apparently had the hostname wrong!

```
$vela login --addr https://vela.company.com
WARN[0000] Unable to find config file @ /Users/fakeusername/.vela/config.yml 
Enter a username: fakeusername
Enter a password: ***********
ERROR:  Post "https://vela.company.com/login": dial tcp: lookup vela.tegrat.com on x.x.x.x:8080: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1510b35]

goroutine 1 [running]:
github.com/go-vela/cli/cmd.authenticate(0xc0000b3880, 0x4, 0x6)
        /github/workspace/cmd/login.go:96 +0x2c5
github.com/urfave/cli/v2.(*Command).Run(0x1b14440, 0xc0000b3600, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc000082480, 0x172eda0, 0xc0000b4008, 0xc0000b2040, 0x4, 0x4, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /github/workspace/main.go:95 +0xd8a
```

It took me a moment to figure out what was wrong because all I could see in my small terminal was a stack trace.

I'd expect a clean non-zero exit with the last line or two telling me what the error was. 

## Value

CLI usability is important. Surfacing errors cleanly and clearly accelerates figuring out what went wrong.

## Definition of Done

If the user supplies an invalid hostname for the `--addr` option, an error line and nothing else should be displayed. Perhaps show more if a `--verbose` option is set.

**Comment by wass3r** [comment]
With the ongoing changes prior to release, the process will change quite a bit and this should not be an issue with the next release.
