### ISSUE TITLE
Move PR skip scenarios to Webhook struct

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#78]
## Description

Per discussion on https://github.com/go-vela/types/pull/86, explore ways to move skip logic for pull request conditions to live with Webhook struct to determine whether hook/build is skippable.

## Value

Utilize common Webhook struct to determine whether a build can be skipped.

## Definition of Done

Current method on Webhook struct that determines whether build can be skipped is able to handle PR scenario above.

**Comment by plyr4** [comment]
closed as complete
