### ISSUE TITLE
Add support for the kaniko flag --single-snapshot

### ISSUE THREAD

**Issue by earwik** [go-vela/community#787]
## Description

Kaniko has a [flag](https://github.com/GoogleContainerTools/kaniko#flag---single-snapshot) for squashing layers in a new image.  I would like to expose this in the vela plugin so we can use it.

## Value

This allows for producing smaller docker images.

## Definition of Done

The flag is exposed and documented

## Effort  (Optional)
1 hour

## Impacted Personas (Optional)
Any user using vela to build docker images with the kaniko plugin

**Comment by wass3r** [comment]
pr is merged
