### ISSUE TITLE
enhance: improve the docs around Pipeline Type

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#790]
## Description

we offer YAML, Go and Starlark, but its tough to find docs on why you would need Go, and some examples of rendering Go/template syntax directly in the base pipeline. same with Starlark, most of the documentation refers to Templates. 

maybe these docs exist, and this can be immediately closed. but on initial pass I couldnt find them.
I expected them to exist here: 
https://go-vela.github.io/docs/templates/tutorials/
or
https://go-vela.github.io/docs/templates/tutorials/go/

**Comment by JordanSussman** [comment]
The current documentation for inline templating can be found within https://go-vela.github.io/docs/templates/#templating-directly-in-velayml.

**Comment by plyr4** [comment]
sweet i overlooked that page. thanks Jordan, i'll just close this then
