### ISSUE TITLE
vela-kaniko: support VELA_REPO_TOPICS to use in labels

### ISSUE THREAD

**Issue by wass3rw3rk** [go-vela/community#798]
## Description

v0.19 adds a feature that allows access to topics attached to repos in the source control provider. add a couple of flags to the vela-kaniko plugin to access these topics to optionally attach them to images as labels.

it would be nice to define a filter that allows the user to hone in on targeted topics they want to consume.

## Value

provide additional meta data to images that are produced by the plugin.

## Definition of Done

a user is able to configure some flags to consume repo topics to attach as metadata to produced images. label name to be determined.

when configured, the end result is an image with the standard vela labels including one containing the topics applied.

## Effort  (Optional)

2

## Impacted Personas (Optional)

all

**Comment by wass3r** [comment]
close the issue prematurely as i mistook it for the issue adding support server side. :shame:
