### ISSUE TITLE
Add rulesets `instance` key

### ISSUE THREAD

**Issue by cognifloyd** [go-vela/community#803]
## Description

Add a new `instance` key under step `rulesets`. This allows a pipeline to skip steps if the pipeline is running on an unexpected vela instance.

Today, we can check `VELA_ADDR` in step commands to opt-in/out on certain instances. A ruleset that can completely remove irrelevant steps during pipeline compilation would be much better.

## Value

I need a Vela instance in the EU, and a different one in the US. Both instances process some of the same repos. Some steps should only run in EU or in US.

I also have seperate dev/prod Vela clusters. Some steps might only apply to one or the other.

## Definition of Done

Add new `instance` yaml key under `step.rulesets` that allows steps to run only on particular cluster(s).

The `instance` check happens during pipeline compilation to remove irrelevant steps.

## Effort  (Optional)

unknown

## Impacted Personas (Optional)

Users that need to distinguish between multiple Vela instances.

**Comment by wass3rw3rk** [comment]
this should be in the next version - thanks for the idea :heart:
