### ISSUE TITLE
enhance: allow passing queue credentials in during registration

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#806]
## Description

basically what the title says, following the paradigm for allowing registration via `SERVER_SECRET` **_and_** `vela add worker` we could allow admins to pass in queue credentials during registration.
since the worker is _already_ blocked from pulling from the queue if no registration is provided anyways, this wouldn't really impact much as far as installation options go.

the reason is to limit what is stored in the worker's plaintext environment. the idea is, the more in-memory the better.

## Value

enhanced security around worker containers. decrease the potential for the queue being an attack vector.

## Definition of Done

if they choose, an admin can not provide queue credentials on startup and opt to provide these credentials during registration.

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

admins only.

**Comment by timhuynh94** [comment]
This issue is addressed in V21 release
