### ISSUE TITLE
Update login auth flow

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#81]
## Description

For a mix of reasons involving https://github.com/go-vela/community/issues/29 and Github changes (https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters) and coinciding `go-github` library updates the login flow for the CLI needs to be updated.

## Value

Users are able to login via the CLI with the most recent (go-)github and JWT changes

## Definition of Done

- using latest go-github library, user is able to log in via the CLI
- CLI (sdk-go) handles expiring JWT tokens
- local storage for tokens happens via system-native credential storage; fallback to disk?

**Comment by JordanSussman** [comment]
GitHub was nice enough to just open source https://github.com/cli/oauth to make this flow significantly easier to implement.

**Comment by wass3r** [comment]
Nice, definitely am familiar the device flow within the github cli and this story was about to implement the other version with the local server only. normally the "problem" with these is that they (rightfully) assume you are directly interfacing with the oauth provider. In our case, you are sort of proxy-ing through the server (which is the real client). regardless, great timing - i'll check it out - thanks.
