### ISSUE TITLE
Allow users to see rendered pipeline file

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#84]
## Description

Users should have the ability to view the rendered pipeline file.

## Value

- Ease troubleshooting when utilizing [templates](https://go-vela.github.io/docs/templates)

## Definition of Done

- User able to request the rendered configuration file via the API
- Stretch goal: display the rendered configuration via the UI

## Impacted Personas (Optional)

- All users of templates

**Comment by kneal** [comment]
We think this implementation would exist server-side because of recent changes made to the compiler. 
https://github.com/go-vela/compiler/pull/81

Once the endpoint exists we would work on propagating it down to the CLI. ( server > sdk-go > CLI )

Ideas for what CLI commands would/could look like:
```
    $ vela validate --template  --yaml   /src/.vela.yml
    $ vela expand   --template  --yaml   /src/.vela.yml -o expanded_template.yml
    $ vela expand   --template  --commit bdc232d42091a64a0860eadc9043439452a483f0 -o
```

**Comment by JordanSussman** [comment]
> We think this implementation would exist server-side because of recent changes made to the compiler.
> [go-vela/compiler#81](https://github.com/go-vela/compiler/pull/81)
> 
> Once the endpoint exists we would work on propagating it down to the CLI. ( server > sdk-go > CLI )
> 
> Ideas for what CLI commands would/could look like:
> 
> ```
>     $ vela validate --template  --yaml   /src/.vela.yml
>     $ vela expand   --template  --yaml   /src/.vela.yml -o expanded_template.yml
>     $ vela expand   --template  --commit bdc232d42091a64a0860eadc9043439452a483f0 -o
> ```

Can we ensure the MVP release includes updates to https://github.com/go-vela/compiler/pull/81 that let the modification determine if the event is "real"? I'm worried about situations where folks utilize the modification service to also perform other tasks beyond simply modifying the `.vela.yml`.

**Comment by kneal** [comment]
I'm not sure what you mean by real, we do believe the expansion process will have to exist within a new set of endpoints because of the way templates and that modification service works. So, I believe the first part of this implementation will be a new set of endpoints that support validation/expansion.

**Comment by JordanSussman** [comment]
> I'm not sure what you mean by real, we do believe the expansion process will have to exist within a new set of endpoints because of the way templates and that modification service works. So, I believe the first part of this implementation will be a new set of endpoints that support validation/expansion.

I suppose "real" in this context is simply distinguishing between modifications of the `.vela.yml` for scheduled builds vs modification of the `.vela.yml` for CLI validation/expansion.

**Comment by davidvader** [comment]
Implemented through 
https://github.com/go-vela/server/pull/203

See there for more discussion on endpoint implementation/potential enhancements

**Comment by davidvader** [comment]
go-vela/server#203 has been postponed and set to Draft while adding required functionality to types

go-vela/server#115
once reviewed and merged, will need to add template SetHTMLURL functionality

**Comment by jbrockopp** [comment]
Adding new `pipeline` endpoints to mock:

https://github.com/go-vela/mock/pull/74

**Comment by jbrockopp** [comment]
Adding new `pipeline` endpoints to sdk:

https://github.com/go-vela/sdk-go/pull/63

**Comment by jbrockopp** [comment]
Adding new `pipeline` commands to CLI:

https://github.com/go-vela/cli/pull/170

**Comment by davidvader** [comment]
UI feature implemented through go-vela/ui/pulls/233
