### ISSUE TITLE
schedule: better handling of commit status limit

### ISSUE THREAD

**Issue by wass3rw3rk** [go-vela/community#841]
## Description

In GitHub you can update the commit status for a sha/context up to 1,000 times, see https://docs.github.com/en/enterprise-server@3.7/rest/commits/statuses#create-a-commit-status. The likelihood for this limit to be hit is higher with scheduled builds resulting in log errors like:

> `{"level":"error","msg":"unable to set commit status for build <org>/<repo>/9001: POST https://<domain>/api/v3/repos/<org>/<repo>/statuses/8968ddf24f66786c669ebd26fe83e3d4cf03a19c: 422 Validation Failed [{Resource:Status Field: Code:custom Message:This SHA and context has reached the maximum number of statuses.}]","time":"2023-07-31T19:00:13Z"}`

The likelihood for this scenario to occur depend on schedule frequency and repository activity (or lack thereof).

A workaround is to make occasional commits to the repo.

Potential solution: only update status if it's different than the current status? it won't prevent it from happening, but reduce the chances in most cases, unless the scheduled build in question is very flaky in terms of success/failure.

## Value

1) Ensures that the commit status accurately reflects the actual status.
2) Reduces log noise.

## Useful Information

potential solution: don't send a status update to SCM for scheduled builds? it doesn't seem useful.

1. What is the output of `vela --version`?

v0.20.x

2. What operating system is being used?

3. Any other important details?

to reproduce, you could set a high frequency schedule (you'd have to set the interval limit to something very low - https://github.com/go-vela/server/blob/main/cmd/vela-server/main.go#L228-L233) - or more than one and not make any commits to the given repo. eventually you will run up against this limit and be faced with the given error.

**Comment by timhuynh94** [comment]
Potential solution:

1. don't send a status update to SCM for scheduled builds. Pros: quick change. Cons: tech debt? It's not useful but could be identified as a bug if someone notices.
2. Only update commit status if it's different than the current status. This can be achieved by utilizing the GetParent() build number. If current build's status is the same as the parent's then no update. If GetParent() build is 0, then commit status will be updated as it's the very first build. Cons: extra calls to DB for every scheduled build
3. Only update commit status if it's different than the current status (SCM). This can be achieved by utilizing the GetCombinedStatus() from github. Only update when status is different. Cons: extra calls to github for every scheduled build.

**Comment by timhuynh94** [comment]
https://github.com/go-vela/server/pull/1046
