### ISSUE TITLE
worker status not reset after setting to error

### ISSUE THREAD

**Issue by wass3rw3rk** [go-vela/community#859]
## Description

After we set the status of a worker to error when it is not able to connect to the queue, we never correct the status once the queue becomes available again. The status will only be "fixed" once the worker picks up a build.

https://github.com/go-vela/worker/blob/v0.20.1/cmd/vela-worker/operate.go#L122

Note: At the time of creation of this issue, the worker status field is not actively used elsewhere in the platform.

## Value

worker should strive to have accurate status reflected

## Useful Information

1. What is the output of `vela --version`?

v0.20.x+

2. What operating system is being used?

3. Any other important details?

**Comment by timhuynh94** [comment]
Steps to replicate error status during queue setup:
- Start up stack with manual worker registration
- Bring down Redis container
- Complete worker registration
- Bring up Redis container
- Error status will stay until a build is picked up by worker

Additional concerns 
- Currently there is no connection check periodically once the queue is setup.
