### ISSUE TITLE
server: repairing a renamed (old) repo creates invalid webhook signatures

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#862]
## Description

see title, archive a repo, rename it, unarchive it, repair the old repo, push to the renamed (same) repo, builds will not trigger based on webhook signature failures.

doesnt happen often, but it is quite confusing

**Comment by timhuynh94** [comment]
current workaround is to source repositories again but now there will be 2 repos (old & new) showing on the UI

**Comment by ecrupper** [comment]
FWIW, this is not a problem with any repo enabled after `v0.20`
