### ISSUE TITLE
Surface "Audit" Errors for Schedules

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#872]
## Description

Whenever a user has a YAML bug in their pipeline, or any other build-breaking error that short-circuits pipeline execution, they can usually find these error in the Audit tab, where we populate the `hook` with the error message.

This is currently not available for schedules. Instead, the error is just logged.

## Value

Users would be able to identify pipeline errors on their own instead of noticing the lack of a build.

## Definition of Done

Users have a way to see an error (if it exists) for a schedule-run

## Effort  (Optional)

Medium

## Impacted Personas (Optional)

Schedule folk + Vela support

**Comment by wass3r** [comment]
added with referenced PR(s)
