### ISSUE TITLE
SPIKE: Investigate re-using build preparation routine found in schedule, webhook, build restart, pipeline visualize, etc

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#874]
## Description

Ref: https://github.com/go-vela/server/pull/995/files#r1376437695

There seems to be an opportunity for aggregating this routine into a single function, which may shed light on any potential discrepancies in the process.

## Value

Dumps a lot of duplicate code if successful

Makes it easier to digest as a new developer

## Definition of Done

Determine feasibility of centralizing this core routine into a single function

## Effort  (Optional)

Med/Low

## Impacted Personas (Optional)

Vela contributors

**Comment by wass3r** [comment]
can this be closed @ecrupper ?

**Comment by wass3r** [comment]
closing as PR has been merged
