### ISSUE TITLE
server: Allow separate QUEUE_ADDR value for worker auto discovery

### ISSUE THREAD

**Issue by tmapes** [go-vela/community#876]
## Description

I propose the ability to set some secondary `VELA_QUEUE_ADDR` variable for use in worker auto-discovery.\
VELA_WORKER_QUEUE_ADDR? Not sure, that's quite verbose, VELA_EXTERNAL_QUEUE_ADDR maybe...

After I updated my server and worker versions from 0.20.0 to 0.21.0, I suddenly couldn't startup my workers anymore.

They were failing to connect to the redis queue, nothing had changed on my end with the redis setup nor did I find anything in the migration docs about queue changes.

I still use the `VELA_SECRET` / `VELA_SERVER_SECRET` method of worker authentication so I didn't pay much attention to the docs around the new worker registration changes.

What I eventually landed on, was even while still using the old auth method, the `VELA_QUEUE_ADDR` variable _on the worker_ was no longer being respected as the queue address.\
Through trial and error I realized the `VELA_QUEUE_ADDR` _of the server_ was being served to the workers.

This introduces a complexity, as my server components run on 1 machine and my workers elsewhere.\
The server was previously configured to connect to the queue via a docker-compose hostname (`VELA_QUEUE_ADDR=redis://vela-redis:6379/0`) however this doesn't work external containers.

The only way I could get my workers up-and-running again, was to force the server itself to connect 'outside' the compose network via the IP address of the physical machine (`VELA_QUEUE_ADDR=redis:////192.168.1.10:6379/0`).

I haven't run actual tests, but based on prior experience with k8s, 'leaving' the virtual network to come back in can cause latency.

## Value

This likely only impacts me, as most larger installations are likely already running `redis` on another server thus they likely were already using a FQDN or externally routable IP address.

Though I would like to go back to having the `server` be able to do its networking 'internally' on the compose network.

## Definition of Done

When some secondary environment variable exists that allows a different queue address to be served to workers.

## Impacted Personas (Optional)

Anyone who happens to be running server and redis on one machine, and workers on others.

**Comment by tmapes** [comment]
This probably isn't super easy to actually do, so feel free to close it and I'll just live with it.

Not like my home lab stuff is so critical that i need to save those milliseconds leaving/entering the docker network.\
Just a nice to have.

**Comment by wass3r** [comment]
i think it's possible. i had to manually override this for local live debugging as well. so i overwrote (in code) what the worker retrieved from the server.

thanks for raising the issue.
