### ISSUE TITLE
Vela Schedules - Add ability to pass parameters to a scheduled build

### ISSUE THREAD

**Issue by KenBakerTGT** [go-vela/community#886]
## Description

Provide ability to specify parameters for a scheduled build.   Think of it like an overide to an environment variable.  
We have jobs that take command line parameters.  Those parameters will have a default value, but on occasion on-demand run will be needed with altered parameters. 
Instead of updating the job/script itself, would be preferred to trigger the schedule as a one-time run and provide the parameters as overrides. 

## Value

More flexible and reusable code. 

## Definition of Done

Ability to request on-demand/one-time executions with custom parameters.

**Comment by JordanSussman** [comment]
Have you taken a look at using [Deployments](https://go-vela.github.io/docs/usage/deployments/) to handle this?

**Comment by wass3r** [comment]
closing. feel free to follow-up if this need is still not met.
