### ISSUE TITLE
Terraform Plugin: When the Terraform apply fails the state is still saved

### ISSUE THREAD

**Issue by brahammittal** [go-vela/community#897]
We are using the Vela Terraform plugin to create SAP BTP infrastructure. If we are getting an error in the apply step, still the state gets saved and we are not able to use the same file to create the infrastructure. We have to change the details on the file to make it work.

We are changing the resource ID in TF file. We have to change the parameters passed to the resource as well to make it work.

**Comment by wass3r** [comment]
I don't believe this to be a bug. As far as I know, this is how terraform works, see https://developer.hashicorp.com/terraform/tutorials/cli/apply#errors-during-apply.

The plugin is just using your configuration and running `terraform apply ...` for you. You can check how the command for this is constructed here, if you're curious: https://github.com/go-vela/vela-terraform/blob/dfaaf57037ddec3078ad0ca4abbe4f7b2dcaa5d9/cmd/vela-terraform/apply.go#L53-L158. If you still believe there's an error in how that's done, please let us know and provide more detail on what sets of parameters you used and what you expected the final `terraform` command to look like versus what the plugin is doing.

I will change the `bug` label to `question` for now.

**Comment by wass3r** [comment]
closing. feel free to comment to re-evaluate.
