### ISSUE TITLE
Enhance shared secrets page

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/community#90]
## Description

- Users should be able to easily find the shared secrets page instead of needing to manually navigate to https://$VELA_URL/-/secrets/native/shared/$ORG/$REPO.
- Users should be able to define the `team` to manage the shared secret on the https://$VELA_URL/-/secrets/native/shared/$ORG/$REPO/add page.

## Value

- Reduce confusion for those wanting to add shared secrets

## Definition of Done

- Users are able to navigate to the shared secrets page without needing to manually enter the address
- Users are able to define the `team` within the add shared secret page

## Impacted Personas (Optional)

Users of shared secrets

**Comment by wass3r** [comment]
this has been merged and released
