### ISSUE TITLE
deployment notice unaware of updated repo state

### ISSUE THREAD

**Issue by wass3rw3rk** [go-vela/community#909]
## Description

This notice when adding a deployment is nice, but doesn't remove itself once deployment:created event is enabled.

![image](https://github.com/go-vela/community/assets/49894298/d92444b8-2d65-43d5-82b6-92159ccec269)

to reproduce:
1. enable repo
1. go to deployments page to add a deployment
1. you will see the above notice
1. navigate to repo settings
1. enable deployment:created event
1. return to add a deployment form
1. notice is still shown even though it is incorrect now

expected:

notice should disappear once the event is enabled

i would propose the following tweaks:
1. rephrase to something like "To trigger builds for deployments, enable a 'Deployment' event on the [Settings]() page for this repo." (or something similar)
1. make deployments aware of updated repo state

## Value

reduce confusion/friction; better ux when adding a deployment via ui

## Useful Information

1. What is the output of `vela --version`?

v0.23.0-rc

3. What operating system is being used?

4. Any other important details?

**Comment by wass3r** [comment]
this seems fixed in the latest version
