### ISSUE TITLE
Non Dialog login for Vela CLI

### ISSUE THREAD

**Issue by brahammittal** [go-vela/community#912]
Hi Team,

Today while using Vela CLI the only option available is to login via browser. Is the login via a non-dialog approach on the roadmap?

We need to call Vela through a batch file, and the login via browser is not helping us.

**Comment by JordanSussman** [comment]
You can pass a [GitHub personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) as a Vela argument to avoid the interactive login. For example: `vela --api.token <github PAT> get repos`.
