### ISSUE TITLE
Add info log during `init` step prior to each download of an image for visibility

### ISSUE THREAD

**Issue by ecrupper** [go-vela/community#915]
## Description

I've noticed this being a more relevant issue when using `vela exec pipeline`. Essentially, if you don't have the image in your local Docker cache, then the pipeline hangs at

```sh
[step: init] > Preparing service images...
[step: init] > Preparing stage images...
[step: init] > Preparing step images...
```

While it downloads the first image. It follows it up with an inspect:

```sh
[step: init] $ docker image inspect golang:latest
sha256:0c4ed86491a49bc887be0382d454058ab30887445728dd1fdb346ebc69395fe9
```

So the simple request is adding a line like 
```sh
[step: init] > Preparing step images...
[step: init] > Downloading golang:latest...

# long pause happens here

[step: init] $ docker image inspect golang:latest
sha256:0c4ed86491a49bc887be0382d454058ab30887445728dd1fdb346ebc69395fe9
```

## Value

People may prematurely cancel their local runs, thinking there is something wrong, as it's not intuitive what's going on, especially if the first image to download is hefty.

## Definition of Done

Informative log added prior to each image download during init step

## Effort  (Optional)

Low

**Comment by wass3r** [comment]
completed in referenced PR
