### ISSUE TITLE
For installation and usage, please visit our user docs...which don't exist

### ISSUE THREAD

**Issue by barrebre** [go-vela/community#93]
Feel free to tell me I need to fill out the entire form below, but my request is quite simple - Your documentation doesn't exist for installation. This is referenced in both your go-vela/vela-tutorials page and vela-docs page. 
https://go-vela.github.io/docs/install/getting-started/

Additionally, your "Please see our proposals documentation documentation for more information." in go-vela/community points to a 404.

**Comment by plyr4** [comment]
let me know where you've found dead links and i'd be happy to fix them.
here are the installation docs (two years late, sorry!)
https://go-vela.github.io/docs/installation/
