### ISSUE TITLE
Reenable "go fix" once the fix for it has been merged

### ISSUE THREAD

**Issue by wass3rw3rk** [go-vela/community#964]
## Description

It looks like there is an issue on Go 1.21.x+ that makes "go fix" not work if you specify x.y.z version in go.mod. the "go fix" part is temporarily commented out until the fix has been released.

Fix the `validate` GitHub actions once the fix has been release by Google (it looks like it's slated for 1.23).

## Useful Information

https://github.com/golang/go/commit/7fd62ba821b1044e8e4077df052b0a1232672d57
https://go-review.googlesource.com/c/go/+/527342
https://github.com/go-vela/server/pull/1101

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?

- [x] https://github.com/go-vela/server/blob/main/.github/workflows/validate.yml
- [x] https://github.com/go-vela/worker/blob/main/.github/workflows/validate.yml
- [x] https://github.com/go-vela/sdk-go/blob/main/.github/workflows/validate.yml
- [x] https://github.com/go-vela/cli/blob/main/.github/workflows/validate.yml
- [x] https://github.com/go-vela/types/blob/main/.github/workflows/validate.yml

**Comment by wass3r** [comment]
go 1.23.0 has been released, so this can be completed at any time.
