### ISSUE TITLE
plugin: add gh cli to vela-git

### ISSUE THREAD

**Issue by plyr4** [go-vela/community#975]
## Description

it would be sweet if users could automatically interact with git using `gh` the official cli. 

we can add it to the plugin, meaning, throw in a `gh` installation into the Dockerfile and call it good 
https://github.com/go-vela/vela-git/blob/main/Dockerfile#L19

but i dont think `gh` supports using the netrc for `gh auth login` so it likely wont work "out of the box" for users unless they provide a PAT  

https://github.com/cli/cli/issues/288
https://github.com/cli/cli/issues/3623

so... if we figure out auth, or move Vela _away_ from netrc then this will be easier. 
or we can just install `gh` and let users figure that out on their own, but i dont think thats the best user experience. personally, i would expect it to "just work".

**Comment by colindean** [comment]
I'm okay with the baby steps approach. Add in the CLI pkg and let the user figure out how to get the token in there for now. Maybe someone will come along and add netrc support in CLI/cli#288 or Vela or this plugin can provision an envvar secret or build the gh-compatible config at runtime.

**Comment by colindean** [comment]
A S.O. question on handling the netrc parsing:

https://stackoverflow.com/questions/30024237/search-netrc-file-in-bash-and-return-username-for-given-machine

**Comment by colindean** [comment]
I polished up something for myself: https://github.com/colindean/hejmo/commit/0062264618a45ec9cd31f072830e38481777a9f3

**Comment by colindean** [comment]
Done in bd222d4f543275c1085025f0f2bdff570a96691c
