### ISSUE TITLE
Improve examples in usage section of documentation

### ISSUE THREAD

**Issue by kneal** [go-vela/community#99]
## Description

Right now the usage section has a set of sample pipelines. We should look to add more samples.

The getting started section should have a set of documentation for best practices around secret types and picking the right one for a use case

## Value

Allows customers to better understand the concepts used within Vela

## Definition of Done

Documentation exists and is merged into the site

## Effort  (Optional)

1-2 days

## Impacted Personas (Optional)

Users of Vela

**Comment by davidvader** [comment]
https://go-vela.github.io/docs/usage/samples/ (in progress)

**Comment by kneal** [comment]
Closing this with @davidvader link, we should have more specific improvements request and not a generic one. This is too broad of a scope.
